angular-ui/ui-grid

src/features/exporter/js/exporter.js

This sets exports to use UTF-8. This prevents encoding errors in some spreadsheet programs such as excel.

add utf-8 support on csv export

---

misc/tutorial/202_cellnav.ngdoc
src/features/cellnav/js/cellnav.js
src/features/cellnav/test/uiGridCellNavDirective.spec.js

Add modifierKeysToMultiSelectCells option which enables user to,
when including cellNav, hold the modifier key to select multiple
cells with the mouse. Add API method getCurrentSelection which
enables the user to get the cells currently selected.

Enh(cellNav) #2186 select multiple cells

---

src/js/core/directives/ui-pinned-container.js

Sometimes width of the header or the canvas were calculated as NaN,
which looks to be a race condition.  Two fixes:
- Use width when drawnWidth not available.  Will potentially fail
if with is '*' or a percentage, but seems to work fine for now
- Call updateWidth if width isn't present

Fix #2542 (renderContainer): mis-render on 401 on initial render

---

misc/tutorial/190_large_dataset.ngdoc
src/js/core/services/rowSearcher.js
test/unit/core/row-filtering.spec.js

Rewrote to replace caching with an explict pre-compile step, moved from
forEach to for loops (apparently helps Chrome optimizer), explicitly
defined some functions, moved some pre-processing out of the loops and
into the explicit pre-process steps.
All unit tests still pass, there is however some risk of regression in this
commit given scale of the changes.

Fix #2574(filtering): performance improvements for large data sets

---

src/js/core/factories/Grid.js

Replace
container.visibleRowCache.length = 0;
With
container.visibleRowCache= [];
Because empty array is being considered as undefined which doesn't have a property called length

Fix Error: container.visibleRowCache is undefined.

---

src/features/selection/templates/selectionHeaderCell.html
src/less/cell.less
src/less/footer.less
src/less/header.less
src/less/rtl.less
src/templates/ui-grid/uiGridHeaderCell.html

This would fix #2579.
I refactored the RTL less hierarchy so it's not as verbose and more readable. I also replaced the vertical-bar div elements with actual CSS borders. This should have a nice effect of removing 1 DOM elements per-cell, and so far I haven't seen any negative effects, including with increasing the grid's border size, but additional testing should be done.

Fix missing final column border issue

---

src/features/resize-columns/test/resizeColumns.spec.js
src/less/header.less
test/unit/core/directives/uiGridCell.spec.js

For me (but not for everyone) in plunker I'm getting the headers
wrapping.  The cause seems to be that the rightmost header cell
border doesn't have any space - so the whole header row
is 1px too wide.  No idea why that happens to me and nobody
else (well, not @swalters or @c0bra).
The header apparently needs content-box for height, aiming to
put border-box on the header-cell, which might sort things out.
This needs verifying on IE11, because the content-box change
was to fix IE11.

Fix plunker: border-box style on headercell

---

src/features/selection/js/selection.js
src/features/selection/test/uiGridSelectionDirective.spec.js

The "isRowSelectable" is a new option that enables to add some logic to whether a row is selectable or not.
The value assigned to the option has to be a function that accepts a row as parameter and has to return a boolean that specifies if the given row is selectable or not.
Here is a sampe of such a function
```javascript
var options = {
isRowSelectable: function(row) {
// every row that has an entity with the name "Grid" is selectable
return row.entity.name === 'Grid';
}
}
```

added "isRowSelectable" to options

---

src/js/core/directives/ui-grid-render-container.js

A follow-up commit to 924af44b7ac7c3087d24427cc5904707da5cdf85 @kenwarner

Fix #2461: let the parent container scroll also on touchmove event

---

misc/tutorial/212_infinite_scroll.ngdoc
src/features/infinite-scroll/js/infinite-scroll.js
src/features/infinite-scroll/test/infiniteScroll.spec.js
src/js/core/constants.js
src/js/core/directives/ui-grid-viewport.js
src/js/core/directives/ui-grid.js
src/js/core/factories/Grid.js
src/js/core/factories/GridRenderContainer.js

Additionally fix display issue for infinite scroll 'blank block' #2535
Code changes enable infinite scroll up. Changes are as follows:
File: misc/tutorial/212_infinite_scroll.ngdoc
Update documentation to load the data for up and adjust the load data
for down to append to exiting data, not overwrite the hashKeys
src/features/infinite-scroll/js/infinite-scroll.js
Updated file to add new needLoadMoreDataTop method and supporting code
to call method.
src/features/infinite-scroll/test/infiniteScroll.spec.js
Updated unit test to test for needMoreLoadDataTop
src/js/core/constants.js
Added new constant for scroll direction
src/js/core/directives/ui-grid-viewport.js
Added supporting logic to set scroll direction properly
src/js/core/directives/ui-grid.js
Added new function to adjust scroll …

Enable Infinite Scroll Up 

---

src/js/core/directives/ui-grid-render-container.js

>When scrolling up, the page continues scrolling when the grid's scroller reaches the top which is good. But the same doesn't happen when the grid's scroller is at the bottom
It seems that the fireThrottledScrollingEvent function had a conflict with the browser scrolling behavior  #1926

scroll bug when scrolling down  #1926

---

src/js/core/services/rowSearcher.js
test/unit/core/services/rowSearcher.spec.js

Example use:
Code:
columnDefs: [
// ...
{
cellFilter: 'date:\'d MMM yyyy H:mm\'',
displayName: 'Order Date',
field: 'date',
filters: [
{
condition: uiGridConstants.filter.GREATER_THAN_OR_EQUAL,
placeholder: 'From',
flags: { date: true }
},
{
condition: uiGridConstants.filter.LESS_THAN_OR_EQUAL,
placeholder: 'To',
flags: { date: true }
}
]
}
// ....
]

Add date flag to filters to be allow columns to be filtered by dates.

---

src/js/core/directives/ui-grid-render-container.js
src/js/core/factories/GridColumn.js
src/js/core/factories/GridRenderContainer.js
src/less/footer.less
src/less/header.less
src/templates/ui-grid/ui-grid-footer.html
src/templates/ui-grid/ui-grid-header.html
src/templates/ui-grid/uiGridViewport.html

Previously header cell heights were calculated based on a "max height is
king" algorithm where cells could grow to match the largest height, but
could never shrink, e.g. this let cells with no filter box be the same
height as those with no filter box.
This presented a problem with toggling features like filtering. If
suddenly no columns were filterable this would leave a big empty space at
the bottom of each header cell.
This change makes header cells display-type "table-cell", which lets them
render like a TD with full height, and places them in table-row and
table divs. Replacing "width" with "min-width" and "max-width" forces the
header cells to be the correct width.
Also the `columnStyle` method has been replaced with a
`columnWrapperStyle` method.

Fix dynamic header heights

---

src/js/core/directives/ui-grid-column-menu.js

The column menus for columns to the right were in the wrong place. This
was due to the change to the header to use a table format, which also
appeared to include using offsetLeft on the parent to reflect virtualised
columns to the left.  Take this offsetLeft into account as well in the
column menu positioning calculations.

Fix (columnMenu): Fix #2852 positioning of column menu once scrolled

---

src/features/exporter/js/exporter.js
src/less/body.less

Information and code provided by @alexandery.  I have no ability to test
it, but it should only impact IE9, which apparently doesn't work otherwise
anyway.
The main concern here is that this creates and destroys an iFrame in IE9,
and that iFrame apparently messes up formatting, so requires application of
width: auto !important; on the ui-grid-viewport.  That appears to break formatting
in chrome on all features tutorial, so I haven't applied it.  Presumably that means
formatting will be ugly in IE9.

Fix (exporter): Fix #2313 export for IE9

---

src/features/exporter/js/exporter.js

isIE() returns false when using browsers other than Internet Explorer,
but it worked as if using IE.
I tested in IE 11, Firefox 36.0, and Chrome 40.0.2214.115 m.
This pull request is related with #2312 and #2873.

Fix export bug around isIE

---

grunt/aliases.js
misc/site/data/500_complex.json
misc/tutorial/209_grouping.ngdoc
src/features/grouping/js/grouping.js
src/features/grouping/less/grouping.less
src/features/grouping/templates/groupingExpandAllButtons.html
src/features/grouping/templates/groupingHeaderCell.html
src/features/grouping/templates/groupingRowHeader.html
src/features/grouping/templates/groupingRowHeaderButtons.html
src/features/grouping/test/grouping.spec.js
src/font/config.json
src/js/core/directives/ui-grid-column-menu.js
src/js/core/factories/Grid.js
src/js/core/factories/GridColumn.js
src/js/core/factories/GridRow.js
src/js/core/services/rowSearcher.js
src/js/i18n/en.js
test/unit/core/directives/ui-grid-column-menu.spec.js
test/unit/core/factories/Grid.spec.js
test/unit/core/factories/GridRow.spec.js

This is a basic grouping function, providing a basis on which we
can extend and debug.  It provides:
- multilevel grouping
- aggregations on any non-grouped columns
- menu items to add/remove grouping
- menu items to add/remove aggregations
- API for manipulating grouping and rows
- groupingRowHeader to expand and collapse grouping.
The code builds on the sort logic, and heavily on the rowProcessor logic.
It adds internal rows to the rendered rows (but not grid.rows), these
are regenerated each time the rowProcessor runs.
It maintains expanded/collapsed state in grid.grouping.rowExpandedStates,
so that this persists across row builds.
It should interact cleanly with filtering and sorting.  It doesn't interact
well with edit and probably some of the other features.  It doesn't work well …

Feat(grouping): alpha release of grouping feature

---

misc/tutorial/209_grouping.ngdoc
src/features/expandable/js/expandable.js
src/features/grouping/js/grouping.js
src/features/move-columns/js/column-movable.js
src/features/pagination/js/pagination.js
src/features/resize-columns/js/ui-grid-column-resizer.js
src/features/saveState/js/saveState.js
src/js/core/factories/Grid.js
test/unit/core/directives/uiGridCell.spec.js

Make queueRefresh (which calls refreshCanvas) and queueGridRefresh
(which calls grid.refresh) available on the api.  Document when
to use which, and what they do.
Change the core application to use queueGridRefresh in preference
to refresh, which means we get a debounce if this was being called
multiple times in a digest - for example once for each column.
Didn't apply to areas that appeared to be waiting on the promise
that it returns - e.g. didn't apply to pinning.

Enh(core): add doco to refresh methods, move to queueGridRefresh

---

src/js/core/directives/ui-grid-menu-button.js
src/js/core/directives/ui-grid-menu.js
src/js/core/factories/GridOptions.js
src/templates/ui-grid/ui-grid-menu-button.html
test/unit/core/factories/GridOptions.spec.js

In 2.x it was possible to specify a custom menu template. In 3.0 the one grid menu has been split into 3 directives and custom templates are not possible. This pull request adds the ability to specify custom templates for menuButton, menu, and menuItem.

Bring back the 2.x menu behavior of custom menu templates.

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

Update column sorting priority to not increment when sort is toggled, remove when unsorted, and to respect priority of columns with suppressRemoveSort by taking their priority in to account when a new column is sorted.

Fix #3036: Update column sorting priority

---

misc/tutorial/212_infinite_scroll.ngdoc
src/features/infinite-scroll/js/infinite-scroll.js
src/features/infinite-scroll/test/infiniteScroll.spec.js
src/js/core/directives/ui-grid.js
src/js/core/factories/GridRenderContainer.js

Substantial refactor of infinite scroll.  Provides new functionality, a much more
detailed tutorial, and removes the code that crept into core in #2730 (which I merged
when I shouldn't have).  Clarifies the handling, removes a viewPort directive that was
unnecessary, makes the handling for scroll up and down consistent.
Strictly speaking the API hasn't changed, but there are some new settings and the
default behaviour has subtly changed in that scrollUp isn't enabled by default.  This
should be more logical to users, but probably does require a review of the tutorial and API.

Fix(infiniteScroll): fix #2730, fix #2827, BREAKING changes

---

misc/api/design-rendering-cycle.ngdoc
misc/tutorial/204_column_resizing.ngdoc
src/features/pinning/js/pinning.js
src/features/resize-columns/js/ui-grid-column-resizer.js
src/js/core/directives/ui-grid-header.js
src/js/core/directives/ui-grid-render-container.js
src/js/core/directives/ui-pinned-container.js
src/js/core/factories/GridRenderContainer.js

Change the style computations with the aim of making them deterministic
and able to calculate widths in a single pass rather than being iterative.
Fix #3050, and somewhat improves #1957, at least to my eye.
Changes are:
- change renderContainer updateColumnWidths to calculate across all
visible columsn in all render containers, rather than trying to calculate
one render container at a time (cannot otherwise work with * and %, these are of
the whole grid, not just one render container)
- change header updateColumnWidths to just rely on the renderContainer, not
do it again itself in a slightly different way
- change updateColumnWidths to be simpler, and to calculate percentages in a way
that I think makes more sense
- change resize feature to not attempt to 'resizeAround' the changed …

Refactor(styleComputations): fixes rendercontainer rendering problems

---

src/features/move-columns/js/column-movable.js

On Safari, the handle to move columns has an offset, which increases the more you have horizontally scrolled (so not really visible when the table has not many columns)
The changes proposed compute differently the initial position of the handle for Safari only.

Incorrect handle offset when moving column on Safari

---

src/js/core/factories/GridRenderContainer.js
src/templates/ui-grid/uiGridViewport.html
test/unit/core/factories/GridRenderContainer.spec.js

The capitalization of viewport in the getViewportStyle method (previously getViewPortStyle) was not consistent with other references to viewport.  This has been changed to be consistent.

fix(GridRenderContainer) Capitalization of viewport

---

src/features/edit/js/gridEdit.js

the uiGridEditService service had an un-used dependency injection, $templateCache, which I removed.

remove unnecessary service injection from 'edit' feature

---

test/e2e/gridTestUtils.spec.js

Add getGrid, getRow, and selectRow helper methods to utils file.
Modified existing methods to use these new helper methods where
appropriate. In reference to issue #2693.

Add helper methods to e2e gridTestUtils.

---

src/features/grouping/js/grouping.js
src/js/core/factories/Grid.js
src/js/core/services/gridClassFactory.js
test/unit/core/row-filtering.spec.js

I also introduced the priority for the processor.
Followed the same style as `registerRowsProcessor(...)` method
Related to #3251

Add registerColumnsProcessor to API

---

misc/tutorial/103_filtering.ngdoc
misc/tutorial/306_custom_filters.ngdoc
src/features/tree-view/test/tree-view.spec.js
src/js/core/directives/ui-grid-filter.js
src/js/core/directives/ui-grid-header-cell.js
src/js/core/factories/GridApi.js
src/js/core/services/gridClassFactory.js
src/templates/ui-grid/ui-grid-filter.html
src/templates/ui-grid/uiGridHeaderCell.html

Similar in concept to #2918, but works with templates rather than directives.
Allows use of widgets other than the standard widgets, and provides a tutorial
on using the capability to produce custom dropdowns and the like.

Enh(filtering): support custom filter template

---

misc/tutorial/103_filtering.ngdoc
misc/tutorial/121_grid_menu.ngdoc
misc/tutorial/306_custom_filters.ngdoc
misc/tutorial/307_external_sorting.ngdoc
misc/tutorial/401_AllFeatures.ngdoc
src/features/exporter/js/exporter.js
src/features/importer/js/importer.js
src/features/saveState/js/saveState.js
src/features/saveState/test/saveState.spec.js
src/js/core/directives/ui-grid-menu-button.js
src/js/core/factories/Grid.js
src/js/core/factories/GridColumn.js
src/js/core/factories/GridOptions.js
src/js/core/services/ui-grid-util.js
src/less/menu.less
src/templates/ui-grid/ui-grid-header.html
test/e2e/gridTestUtils.spec.js
test/unit/core/factories/GridOptions.spec.js
test/unit/core/services/ui-grid-util.spec.js

Fix #3236: doco on columnDef types
Fix footer: aggregation wasn't running on first load, changed the throttle to do one last call afterwards, changed throttle to $interval rather than $timeout to avoid breakage on e2e tests (protractor doesn't like $timeout)
Enh e2e tests: added a check for filter dropdowns
Fix e2e tests: fixed a variety of breakage in the e2e tests
Enh gridMenu: support for ordering on menu items, they were not deterministic and therefore sometimes in different orders
Enh saveState: allow saving of treeView state

A variety of fixes

---

misc/demo/modal.html
src/js/core/directives/ui-grid.js
src/js/core/directives/ui-pinned-container.js
src/js/core/services/ui-grid-util.js
src/less/header.less
src/less/menu.less
test/unit/core/services/ui-grid-util.spec.js

This is a fix for #2700 and a few other issues.
The problem here is that for determining the grid width, gridUtil is detecting that when the grid is initialized, it has an offsetWidth of 0, so it creates a "fake" (cloned) element that it attaches to the document with visibility: hidden in order to measure it.
This causes a problem because with width: 100% when attached to the document body the grid will just fill up the whole space. THEN when the real grid is in the modal it takes up way more space than it should.
This change makes the grid wait up to 2 seconds for the element to have a width > 0 before it initializes the dimensions.
Note that this change also has a breaking change, which is that gridUtil can no longer try to get the width of hidden elements, which is the same as jQuery. …

fix(uiGrid): Wait for grid to get dimensions before rendering

---

src/features/exporter/js/exporter.js

The exporterOlderExcelCompatibility option wasn’t being used to determine whether to prefix the CSV file with "\uFEFF" or not.  See #2646 for more info.

exporterOlderExcelCompatibility fix

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

I had a use-case where I needed a button that clears all filters applied to all columns. This pull request adds a method to the Grid class, `clearAllFilters()`, which does that.

Add Grid.prototype.clearAllFilters() method.

---

Gruntfile.js
misc/tutorial/209_grouping.ngdoc
misc/tutorial/401_AllFeatures.ngdoc
src/js/core/directives/ui-grid-footer-cell.js
src/js/core/factories/Grid.js
src/js/core/factories/GridColumn.js
src/js/core/services/ui-grid-util.js
test/unit/core/factories/GridColumn.spec.js

A handful of issues, mostly comes down to poor use of $interval in the throttle method (my
change), and also fixing a defect where the aggregations weren't calculated by turning the
throttle into a trailing throttle.  This resulted in the grid waiting 0.5s before running the
aggregation, but the aggregation triggered a $digest since a bound value had changed, and in turn
that called aggregation again.
Moved the aggregation call to be triggered by the rowsRendered event.  This event is emitted
whenever visible rows change, which should suit aggregation.  This meant I had to move the
call to aggregation into the gridFooterCell, as I needed a destroy event in order to destroy the
registered api listener.
Fixes #3316

iPad performance - spare watchers and aggregations

---

misc/site/index.html

Make consistent with;
http://ui-grid.info/docs/#/api
http://ui-grid.info/docs/#/tutorial
Originally ga-gears which communicates "settings", link is served better by "book"

Update index.html Make "Tutorial" icon book

---

src/features/selection/less/selection.less
src/less/cell.less
src/less/variables.less

Fix for [#3281](https://github.com/angular-ui/ng-grid/issues/3281)
'!important' in cell.less & selection.less
In addition to updating the css selectors and removing !importants, I added a less variable for the .ui-grid-row-header-cell background color

Fix(less): removed importants in favor of higher priority selector #3281

---

misc/demo/pinning.html
src/features/pinning/less/pinning.less
src/js/core/directives/ui-pinned-container.js
src/js/core/factories/GridRenderContainer.js
src/less/header.less
src/templates/ui-grid/ui-grid.html
src/templates/ui-grid/uiGridRenderContainer.html

Pinned containers were wrapping in certain scenarios where grids were being resi
zed. It looked to the end-user like a poorly-rendered flash, and could possibly
happen over and over during resizing.
This fix uses margins to offset the body render container from the the left and
right render containers
Fixes #2997, Fixes #1957

Fix grid reflow/wrapping issue

---

src/features/resize-columns/js/ui-grid-column-resizer.js
src/js/i18n/de.js

Please, merge it, 'cause grid isn't loading if 'de' language selected and grouping enabled.

Added missed grouping translations for 'de'

---

src/classes/rowFactory.js

Fix: Commit # 24155ad breaks group by field if the field is missing in any of the row. This is because of val.toString() which doesn't work on undefined.
http://plnkr.co/edit/9TaFbiAIsVSAObPpcgO4?p=preview
Should be changed to:
<pre>val = (val === "" || val === null || val === undefined) ? 'null' : val.toString();</pre>

Fixed to handle undefined field when grouping

---

src/features/grouping/js/grouping.js

Happens sometimes (depends on sorting order) when having 2 or more colums with sorting and one of the sorted columns has also grouping
TypeError: Cannot read property 'expandedState' of null
at Object.service.setVisibility (http://localhost/SomeProject/Scripts/angular/ui-grid-3.0.0.rapp.js:16607:63)
at Grid.service.groupRows (http://localhost/SomeProject/Scripts/angular/ui-grid-3.0.0.rapp.js:16355:21)
at startProcessor (http://localhost/SomeProject/Scripts/angular/ui-grid-3.0.0.rapp.js:4160:33)
at handleProcessedRows (http://localhost/SomeProject/Scripts/angular/ui-grid-3.0.0.rapp.js:4176:20)
at processQueue (http://localhost/SomeProject/Scripts/angular/angular-1.4.0-beta.6.js:14030:28)
at http://localhost/SomeProject/Scripts/angular/angular-1.4.0-beta.6.js:14046:27
at Scope.$eval …

Fix null reference in grouping.js

---

src/features/grouping/js/grouping.js

to group null and undefined values together.
Fixes #3271

feat(grouping): Add option groupingNullLabel, 

---

src/js/core/factories/GridRow.js

Not sure if intended but clearThisRowInvisible is not using the parameter "reason" when deleting the "invisible reason" but it always deletes the hardcoded parameter "user". 
This shouldn't change any other behavior since ui-grid internal functions call this function only with the parameter "user" but it will fix any unexpected behavior when using this function with a custom invisible reason
Haven't put a check if the value exists since "delete" fails silently in that case

fix(clearThisRowInvisible) not using parameter reason

---

src/features/move-columns/js/column-movable.js

account for width of left container when positioning moving column header.
Fixes #3417, #3395

fix(moveColumn): account for width of left container

---

misc/tutorial/320_complex_grouping.ngdoc
src/features/tree-base/js/tree-base.js
src/features/tree-base/test/tree-base.spec.js

Change the treeBase.numberLevels variable to consider a single level as 1 instead of 0
Previously there was no way to use this variable to differentiate between a single tree level
and no grouping at all. This does not impact row.treeLevel, which is still zero-based.
Reset treeBase.numberLevels each time the tree is created.
Remove unneeded dependency for groupingService in treeBase.uiGridViewport directive
Add treeRowHeaderAlwaysVisible=false option to complex grouping tutorial (320).
Fixes: #3572

fix(treeBase): Change calculation of number of levels in tree

---

src/js/core/factories/Grid.js
test/unit/core/factories/GridColumn.spec.js

When generating unique column names, do not consider the displayName.
Increment column name property only, using the field as the base.
Increment displayName property only if it is auto-generated,
displaying any provided displayName unchanged.
Fixes: #3453

fix(uiGridColumns): Fix auto-incrementing of column names

---

src/js/core/factories/Grid.js

Refactor setting of header heights to be more DRY and ensure that rebuildStyles
is set when an explicit height is set. Do not set existing explicit heights to
null before recalculating height.
Fixes: #3394, #3382, #3409

fix(uiGridHeader): ensure that styles are rebuilt on explicit height

---

lib/grunt/utils.js

Speeds up tests when working on a specific feature, by skipping unit tests for
all other features.
Use it like grunt test --feature=tree-base

Enh(grunt): add "feature" option to test only one feature

---

DEVELOPER.md

The documentation says the grunt launch task should use angular 1.3.6 however the build has angular version 1.3.7.

Update DEVELOPER.md with correct grunt angular version run paramaters

---

misc/tutorial/209_grouping.ngdoc
src/features/grouping/js/grouping.js

Change the grouping processor to use the sortingAlgorithm for each column,
instead of strict equality for determining group membership.
Change implementation of aggregationFinalizerFn on grouped columns to support
customTreeAggregationFinalizerFn.
Never show counts for date columns, since they will almost always have a
cellFilter applied and changing the data type to a string will break that.
Fixes #3629

Fix(grouping) change group comparison to use sortingAlgorithm

---

lib/grunt/plugins.js

See also discussion on #3617. And because it is overridden by this commit: https://github.com/angular-ui/bower-ui-grid/commit/4615685f3f7a4a4a15b1a4ee80b82da31d41d5ee#diff-0a08a7565aba4405282251491979bb6bL14

Allow users to use Ui-Grid with Angular Version 1.3.x

---

src/js/core/services/rowSorter.js

Add a check to ensure that parameters passed into sorting function are indeed `Date` objects prior to calling `getTime()` on them

Handle date strings in date sort function

---

misc/tutorial/208_save_state.ngdoc

The saveSelection option was missing in the list

Add saveSelection to save state doc

---

src/features/move-columns/js/column-movable.js
src/js/core/directives/ui-grid-header-cell.js

This is primarily to deal with a bug in chrome where move events are
sometimes triggered even when the cursor does not move.
Fix #3333

Fix(moveColumn): ignore move events without movement

---

test/e2e/gridTestUtils.spec.js

This reduces a lot of duplicate code.
Example before this:
it('should have 6 columns', function() {
gridTestUtils.expectHeaderColumnCount('users-table', 6);
gridTestUtils.expectHeaderCellValueMatch('users-table', 0, 'ID');
gridTestUtils.expectHeaderCellValueMatch('users-table', 1, 'Name');
gridTestUtils.expectHeaderCellValueMatch('users-table', 2, 'Email');
gridTestUtils.expectHeaderCellValueMatch('users-table', 3, 'Group');
gridTestUtils.expectHeaderCellValueMatch('users-table', 4, 'Last Login');
gridTestUtils.expectHeaderCellValueMatch('users-table', 5, 'Action');
});
Example after this:
it('should have 6 columns', function() {
gridTestUtils.expectHeaderColumns('users-table', [
'ID',
'Name',
'Email',
'Group',
'Last Login',
'Action',
]);
});

Add expectHeaderColumns() to gridTestUtils.

---

test/e2e/gridObjectTestUtils.spec.js

Before:
var gridTestUtils = require('lib/gridTestUtils.spec.js');
gridTestUtils.expectHeaderColumnCount('users-table', 6);
gridTestUtils.expectHeaderCellValueMatch('users-table', 0, 'ID');
gridTestUtils.expectHeaderCellValueMatch('users-table', 1, 'Name');
gridTestUtils.expectHeaderCellValueMatch('users-table', 2, 'Email');
After:
var GridObjectTest = require('lib/gridObjectTestUtils.spec.js');
var usersGrid = new GridObjectTest('users-table');
usersGrid.expectHeaderColumnCount(6);
usersGrid.expectHeaderCellValueMatch(0, 'ID');
usersGrid.expectHeaderCellValueMatch(1, 'Name');
usersGrid.expectHeaderCellValueMatch(2, 'Email');

Add gridObjectTestUtils.

---

src/js/core/directives/ui-grid-one-bind.js
test/unit/core/directives/ui-grid-one-bind.spec.js

Adds a series of one bind directives that allow simple bindings that reduce the number of watchers on the dom. This is primarily implemented so that the accessibility aria roles wont increase the number of watchers.
Directives added:
- uiGridOneBindAlt
- uiGridOneBindAriaLabel
- uiGridOneBindAriaLabelledby
- uiGridOneBindAriaLabelledbyGrid
- uiGridOneBindClass
- uiGridOneBindHref
- uiGridOneBindHtml
- uiGridOneBindId
- uiGridOneBindIdGrid
- uiGridOneBindSrc
- uiGridOneBindStyle
- uiGridOneBindText
- uiGridOneBindTitle
- uiGridOneBindValue

Adds ui-grid-one-bind directive set to core

---

src/services/DomUtilityService.js

Calculation of pinned column's new left while scrolling will occur floating point under Chrome. Let domUtilityService.setColLeft also be able to support floating point value.

fix #3560 pinning column got malfunctioned when chrome not zoom to 100%

---

src/js/core/factories/GridApi.js

Fixed an issue where only the last found listener passed to GridApi.prototype.suppressEvents would actually be suppressed. (The foundListeners variable was being overwritten at each iteration.)

GridApi.suppressEvents should suppress all the handlers

---

src/directives/ng-grid.js

If columns are lazy loaded, and sortInfo is populated prior to the columns loading, the sortInfo is not applied to the columns. Fixing that.
The following is a plunker that demonstrates the issue:
http://plnkr.co/edit/jMX4JAE6I3kTCcnEIeaZ?p=preview

Applying sortInfo to lazy loaded columns

---

src/directives/ng-header-cell.js

When $compileProvider.debugInfoEnabled(false) then element.scope() doesn't work. As a workaround, put $scope back on each header element.
https://docs.angularjs.org/api/ng/function/angular.element

Make columns reorderable when debug false

---

src/js/core/services/gridClassFactory.js
test/unit/core/services/GridClassFactory.spec.js

We have stored some precalculated data in UI-grid's row with the ```$$``` prefix which we access in the column with Angular's filter. Regardless of if that is the best solution or not, I found the following unexpected behaviour:
A cell filter
```
testSetup.col.cellFilter = 'customCellFilter:row.entity.$$internalValue';
```
causes cell's filter template to be replaced with
```
customHeaderCellFilter:row.entity.$internalValue
```
. It is missing one dollar sign.
This is caused by [String.prototype.replace()'s] (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/replace) special replacement patterns. We can prevent this by passing the second parameter with an anonymous function in ```gridClassFactory.js```.

Ensure cellFilters in gridClassFactory are passed without modifications

---

src/js/core/directives/ui-grid-one-bind.js

The $scope.$watch used `===` for equality comparisons by default and 1.3
uses `angular.equals`. The desired behaior is acheived using
`angular.equals`.

Fixes one bind tests failing with Angular 1.2

---

src/features/saveState/js/saveState.js
src/features/saveState/test/saveState.spec.js

This request is related to the issue numbered #3795.
`restoreColumns()` raises `sortChanged()` with proper arguments as the event doc says.

 #3795 raise sortChanged with proper arguments when grid state is restored

---

src/js/core/factories/Grid.js

The documentation had `@params` instead of `@param` causing the documentation to not be generated correctly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3895)

Fixes documenation typo in Grid.js

---

misc/tutorial/320_complex_grouping.ngdoc
src/features/tree-base/js/tree-base.js

Check for the `showColumnFooter` grid option in tree base, if present
without a aggregationType, use the treeAggregationFn.
Fix several incorrect documentation references in treeBase
Closes #3822
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3898)

Enh(grouping) Support for column footer in treeBase

---

misc/tutorial/320_complex_grouping.ngdoc
src/features/grouping/js/grouping.js

`aggregationChanged` and `groupingChanged` events added to the grouping publicApi
Closes #3868
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3906)

Enh(grouping)Add events to grouping

---

src/features/resize-columns/js/ui-grid-column-resizer.js
src/features/resize-columns/test/resizeColumns.spec.js
src/js/core/factories/GridColumn.js
test/unit/core/factories/GridColumn.spec.js

This fixes issue #3880. The width of the column definition should have precedence over the current column width.
Maybe it'd be better to put that block of code into a separated method?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3897)

Updating column width when columnDefs changes

---

misc/tutorial/102_sorting.ngdoc
misc/tutorial/103_filtering.ngdoc
misc/tutorial/401_AllFeatures.ngdoc
src/js/core/factories/Grid.js
src/js/core/factories/GridColumn.js
src/js/core/services/rowSearcher.js
src/js/core/services/rowSorter.js
test/unit/core/factories/Grid.spec.js
test/unit/core/row-filtering.spec.js
test/unit/core/row-sorting.spec.js

Add getCellDisplayValue to grid core. This returns the cell value after any `cellFilter` has been applied.
Add `columnDef` options `filterCellFiltered` and `sortCellFiltered`, which apply the sort and filter respectively using `grid.getCellDisplayValue` instead of `grid.getCellValue`.
Closes #2839 #3791
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3905)

Enh(filter and sort) Support filter and sort by displayed value

---

src/features/tree-base/js/tree-base.js

Compute footer aggregation even when there are no grouped columns.
Re: #3822
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3907)

Fix bugs in footer aggregation in grouping

---

src/js/core/services/ui-grid-util.js

Fixes a few of the simple documentation problems in ui-grid-util.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3922)

Fixes documentation in ui-grid-util.js

---

src/features/pagination/js/pagination.js

There was a `;` that caused the example to fail to run.
Closes #3945
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3949)

Fixes documentation example bug in pagination.js

---

src/js/core/factories/GridColumn.js

Removes redundant, duplicate and outdated constructor definition.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3952)

Documentation Fix GridColumn.js

---

src/js/core/directives/ui-grid-menu-button.js

If the columnDef config object doesn't include a displayName property and grid.options.enableGridMenu = true, the grid menu titles default to the name property provided in the columnDef config object. This results in an inconsistency between the column headers and the grid menu titles.
More specifically, the column headers are converted to friendly display names via gridUtil.readableColumnName, whereas the menu titles simply display the name property.  
To remain consistent, the menu title should also create a friendly display name via gridUtil.readableColumnName.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3979)

Convert menu item title names to readable column names

---

misc/demo/pinning.html
src/js/core/directives/ui-grid-render-container.js
src/js/core/directives/ui-grid-viewport.js
src/js/core/factories/GridRenderContainer.js

Containers that have overflow: hidden set are not able to naturally scroll
to 100%, because they cannot handle native scroll events; only mousewheel. It's a long discussion; see #3772 for notes.
This change catches a mousewheel event that should put the container at
the max scroll position (basically scrollHeight - offsetHeight) and
manually sets the scrollTop to that amount.
Fixes #3772
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3980)

fix(Grid): Force scroll to 100% when necessary

---

README.md

Grunt build uses pkg.name which is `ui-grid`. Documentation uses . as a separator. 
- Change url in README.md

Wrong url in README.md

---

src/features/pagination/templates/pagination.html

Seems like a given that there shouldn't be a dropdown if paginationPageSizes only contains a single option. This renders as a span if `grid.options.paginationPageSizes.length <= 1` and only renders a dropdown if `> 1`.

paginationPageSizes as label if singular

---

package.json
src/less/bootstrap/bootstrap.less
src/less/main.less

This allows the twitter bootstrap less elements to be used inside of
ui-grid without causing naming conflicts.
Bootstrap less components only get imported if they are used in the less files.
Twitter Bootstrap elements can be used inside of the less files by using the namespace `#ui-grid-twbs`
Example:
````less
button {
#ui-grid-twbs > .btn;
#ui-grid-twbs > .button-size(1px; 1px; 10px; 1; 2px);
#ui-grid-twbs > .button-variant(@headerGradientStart, @headerBackgroundColor, @paginationButtonBorder);
}
```
This allows ui-grid to take advantage of the many browser workaround and fixes that bootstrap has already implemented. This means we can take advantage of its power without needing to worry about it increasing the size of the css file. At the same time it won't cause conflicts with other …

Adds twitter bootstrap less files under a namespace

---

src/features/edit/templates/cellEditor.html
src/features/edit/templates/dropdownEditor.html
src/features/edit/templates/fileChooserEditor.html
src/features/expandable/templates/expandableRow.html
src/features/expandable/templates/expandableRowHeader.html
src/features/expandable/templates/expandableScrollFiller.html
src/features/expandable/templates/expandableTopRowHeader.html
src/features/exporter/templates/csvLink.html
src/features/importer/templates/importerMenuItem.html
src/features/pagination/templates/pagination.html
src/features/selection/templates/gridFooterSelectedItems.html
src/features/selection/templates/selectionHeaderCell.html
src/features/selection/templates/selectionRowHeader.html
src/features/selection/templates/selectionRowHeaderButtons.html
src/features/selection/templates/selectionSelectAllButtons.html
src/features/tree-base/templates/treeBaseExpandAllButtons.html
src/features/tree-base/templates/treeBaseHeaderCell.html
src/features/tree-base/templates/treeBaseRowHeader.html
src/features/tree-base/templates/treeBaseRowHeaderButtons.html
src/templates/ui-grid/ui-grid-filter.html
src/templates/ui-grid/ui-grid-footer.html
src/templates/ui-grid/ui-grid-grid-footer.html
src/templates/ui-grid/ui-grid-header.html
src/templates/ui-grid/ui-grid-row.html
src/templates/ui-grid/uiGridCell.html
src/templates/ui-grid/uiGridFooterCell.html
src/templates/ui-grid/uiGridHeaderCell.html
src/templates/ui-grid/uiGridMenu.html
src/templates/ui-grid/uiGridRenderContainer.html
src/templates/ui-grid/uiGridViewport.html

Makes all of the templates multiline to reduce the number of merge conflicts. This also makes git blame easier to use as each tag change will be line dependent.
This makes the entire code base much cleaner.

Makes AllTemplates Multiline

---

src/features/edit/js/gridEdit.js

I have re-ordered the endEdit() code to trigger the grid focus before the scope destruction and edit control removal. This will allow for the blur event to fire and update the scope.
This will allow ng-model-options="{ updateOn: 'blur'}" on custom edit templates to work.

Fixed ng-model-options="{ updateOn: 'blur'}" on custom edit templates

---

src/js/core/factories/GridRenderContainer.js

I ran the tests and I got:
```
Failures:
1) ui-grid tutorial/103_filtering first grid on the page, filtered by male by default grid should have seven visible columns
Message:
Expected 8 to equal 7.
```
which I have even without my changes.
Do I need to provide anything else?

Fix #4046 - Last column disappearing upon edit

---

src/js/core/factories/GridRenderContainer.js

- renamed wrongly named 'registerViewportAdjuster' fn to 'removeViewportAdjuster'
- when checking if a function is in the viewportAdjusters array need to check that its index is > -1

GridRenderContainer.js registerViewportAdjuster bug fix

---

src/js/core/factories/Grid.js

The documentation was structured to infer that it was not returning a callback.

docs(core): Fixes event callback documentation

---

src/js/core/factories/GridColumn.js

The `priority` property wasn't documented in GridColumn.js

docs(core): Adds priority to sort in columnDef

---

grunt/aliases.js
grunt/copy.js
grunt/cut-release.js
lib/grunt/plugins.js

Less files are now added to the release as part of the grunt release task.
To test this you can run `grunt clean build copy:less_dist cut-release`

chore(build): Adds Less files to release

---

misc/site/index.html

Updated the link to match the tutorial href on the nav bar

Fix homepage tutorial link taking you to localhost

---

src/features/grouping/js/grouping.js
src/features/grouping/test/grouping.spec.js

Grouping was not calling sort changed which meant that external sorting
with grouping wasn't working.
- Adds a call to raise a `sortChanged` event when grouping.
- Additionally adds a test to grouping to ensure that this event is
raised.
Closes #4155

fix(grouping): Grouping now raises a sort changed event

---

src/less/icons.less

This fixes #4113. Simple change.

Fix ttf path by removing '?'.  Resolves webpack issue.

---

src/features/pagination/js/pagination.js

When initially loading a grid with `ui.grid.pagination` and **external pagination** enabled, **paginationChanged** is triggered twice since the watcher values transition from `undefined` to the **initial value**
Found while developing a `pageSize` feature on an alternate pagination project: https://github.com/michaelbromley/angularUtils/issues/212

fix(pagination): avoid initial double firing of `paginationChanged`

---

src/js/core/directives/ui-grid-render-container.js
src/js/core/services/ui-grid-util.js

Previously, the stopPropagation function was not on scrollEvent, causing scrolling in subgrids to also scroll the main grid.  This PR exposes stopProp and calls it on subgrid scroll
fixes #4156

fix(expandable): fix #4156 by calling stopProp on subgrid scroll

---

src/features/cellnav/test/uiGridCellNavService.spec.js
src/js/core/directives/ui-grid-menu-button.js
src/js/i18n/cs.js
src/js/i18n/da.js
src/js/i18n/de.js
src/js/i18n/en.js
src/js/i18n/es.js
src/js/i18n/fa.js
src/js/i18n/fi.js
src/js/i18n/fr.js
src/js/i18n/he.js
src/js/i18n/hy.js
src/js/i18n/it.js
src/js/i18n/ja.js
src/js/i18n/ko.js
src/js/i18n/nl.js
src/js/i18n/pt-br.js
src/js/i18n/pt.js
src/js/i18n/ru.js
src/js/i18n/sk.js
src/js/i18n/sv.js
src/js/i18n/ta.js
src/js/i18n/zh-cn.js
src/js/i18n/zh-tw.js
test/unit/core/directives/ui-grid-column-menu.spec.js
test/unit/core/directives/ui-grid-menu-button.spec.js

I add a new menu label action call "Clear all filters". This action clear all existing filters in the grid. To enable you have to have enableFiltering = true.

feat(core): Add Clear all filters to grid menu

---

src/features/resize-columns/js/ui-grid-column-resizer.js
src/js/core/factories/GridColumn.js

Previously, if a user resized a column and the data were reset, the column size would also be reset.  Instead, disable this behavior by default and add a flag (`allowCustomWidthOverride`) to allow it.  Code originally taken from https://github.com/mage-eag/ui-grid/commit/966c4d98bd7d0ab09e04936d564870cbeaa5c2a9
Fixes #4005

fix(columns): don't reset resized columns on data reset by default

---

FIRST_TIMER.md

I've fixed up some old references to ng-grid in FIRST_TIMER.md. It was instructing people to do things like set ng-grid.git as the upstream project (which would have worked, but I think this is now less confusing). Oh, and fixed a typo too. Small change I know, but I wanted to get to grips with your build process.

Fix misleading references to ng-grid and a typo

---

misc/tutorial/216_expandable_grid.ngdoc

The third paragraph in http://ui-grid.info/docs/#/tutorial/216_expandable_grid has a number of typos. This pull request provides some edits that should improve readability.

Fix typos in 'tutorial/216_expandable_grid'.

---

src/js/core/services/gridClassFactory.js

ui-grid fails when template is defined as a function, for example:
````
$templateCache.put('ui-grid/uiGridCell', function (elem, attrs) {
return "<div class=\"ui-grid-cell-contents\" title=\"TOOLTIP\">{{COL_FIELD CUSTOM_FILTERS}}</div>"
});
````

Support function templates

---

src/js/core/factories/GridColumn.js
test/unit/core/factories/GridColumn.spec.js

- String and number are both allowed.
- Valid String value will parse into number properly.
- Invalid String value will throw an error.

fix(core): fix #4180 by adding validity check for minWidth and maxWidth

---

src/js/core/factories/GridOptions.js

docs(typo) Fix typo and grammatical issue in flatEntityAccess documentation.

docs(typo) Fix typo and grammatical issue in flatEntityAccess

---

grunt/aliases.js
grunt/concat.js
grunt/copy.js
misc/site/customizer/index.html
misc/site/index.html
misc/site/js/customizer.js

The less customizer was broken when bootstrap was added for less mixins.
The less customizer now uses the newest version of less.js and compiles
all of the less files using imports instead of a concatinated file.
Feature less files are still not included in the customizer
unfortunately.
Closes #4079
Closes #3918
Related #4173

fix(customizer): Fixes less customizer in docs

---

src/features/cellnav/js/cellnav.js

Cell nav was throwing an error when you had a field defined like `'1.b'`
Resolved by using the `getQualifiedColField` method on the gridRow.
Closes #4258

fix(cellNav): Error when field defined with number

---

src/features/move-columns/js/column-movable.js
src/features/move-columns/test/column-movable.spec.js

Cache the column order when columns are moved, and restore that order using a dataChangeCallback.
Fixes #4254

fix(moveColumns) Restore column order after altering columnDefs array.

---

CONTRIBUTING.md

Update the text as per the updated repository name.

Updated the text ng-grid to ui-grid.

---

src/features/infinite-scroll/js/infinite-scroll.js

The current implementation causes the scroll position to jump around when new data is loaded and/or when data is removed from the grid. This is largely due to not accounting for the size of the viewport correctly when calculating new scroll percentages, but also because the getViewportHeight function does not appear to correctly account for the space taken up by filters if enabled and the horizontal scrollbar in the example below.
This pull request significantly reduces the jumping. The difference can be seen when scrolling in the two Plunkers below:
**Without changes:**
http://plnkr.co/edit/DfXkANDYkBOmjauF1HmF?p=preview
**With changes:**
http://plnkr.co/edit/pZwFdlK2iHWJqLEwDTrq?p=preview
This pull request does not fix the flickering that occurs when data is removed from the grid. I …

Partially fix jumpy infiniteScroll scrolling

---

src/features/grouping/js/grouping.js

fix issue #4315 ,
simply return the original columns array, instead of null.

fix the moveGroupColumn bug, return original columns instead of null

---

src/less/header.less
src/templates/ui-grid/uiGridHeaderCell.html

The headers now show the sort priority of the column.
This is done using a subscript tag that is pulled closer to the sort
direction icon.

feat(core): Adds sort priority number to header

---

src/features/expandable/js/expandable.js
src/features/expandable/less/expandable.less
src/features/expandable/templates/expandableRow.html
src/features/expandable/templates/expandableScrollFiller.html

I have rebased+squashed PR #3201 of @yccteam.

Dynamically expanded row height

---

misc/tutorial/102_sorting.ngdoc
src/js/core/factories/Grid.js
src/js/core/factories/GridColumn.js
test/unit/core/factories/Grid.spec.js

Alternative to #4338, addressing #4242 in a different way.
This option allows you to specify how a column's sort direction should
be cycled as the heading is repeatedly clicked. The default value,
[null,ASC,DESC], preserves the existing behavior.
I decided to disallow repeating values like [null,ASC,ASC,ASC,DESC] since that would require keeping track of the index explicitly, and I didn't want to add any more fiddly internal state variables.
@benheymink I think that this logic should handle your use case, if I understand correctly. Setting the cycle to [ASC,DESC] on all columns should result in sorting by one column at a time (the most recently clicked one), but the sort won't be removed by repeated clicks on the same column.

feat(core): add sortDirectionCycle column option

---

test/e2e/gridTestUtils.spec.js

There's a bug in `gridTestUtils.expectRowCount` when there are pinned columns. It will get doubled row counts, one for pinned(in `.ui-grid-render-container-left`), the other for main(in `.ui-grid-render-container-body`).
This commit solves the issue.

Fix bug: expectRowCount will get doubled row count if there're pinned columns

---

src/features/pagination/less/pagination.less

In Chrome/IE11 on Windows the pager select wasn't showing more than 2 digits
Fix for #4380

fix(pagination): fix pager select not showing 3 digits on some browsers

---

src/templates/ui-grid/uiGridHeaderCell.html

The sort priority was starting at 2 when the headers or menu buttons
were used to sort. Unfortunately, this will show up strangely for users
who use sort priority 0 when configuring the grid settings.

fix(core): Fixes sort priority starting at 2

---

src/features/infinite-scroll/js/infinite-scroll.js

detect if more data needs to be loaded after the initial load. Before if
not enough data was loaded to enable scrolling, no more data would be
loaded. Resolves issue [4363](https://github.com/angular-ui/ui-grid/issues/4363)

fix(infinite-scroll): load more data if needed

---

src/features/exporter/js/exporter.js
src/features/exporter/test/exporter.spec.js

The CSV export should now show/hide the header values depending on the value chosen for the showHeader grid option.

Hide header in CSV export. #4307

---

src/js/core/factories/Grid.js

Current `modifyRows` documentation does not indicate the need to pass `newRawData` parameter.  Also doesn't explain purpose or use of function (e.g. to immediately select rows after load without $timeout/$interval or to persist selection after data load).
Thought I would update this after reading: #2267

Update Grid.js modifyRows documentation to match function code

---

src/js/core/factories/Grid.js

Hopefully this displays the pseudo-code as intended.  Not sure if Markdown code block start and end syntax is supported in the help guide renderer.

Clean up format of modifyRows function

---

src/js/core/directives/ui-grid.js

Resolves https://github.com/angular-ui/ui-grid/issues/4386
This is quite a nice performance improvement in grids that have rapidly updating data

perf(core): Don't rebuild columns and precompile cell templates each time data is changed

---

src/features/selection/js/selection.js

This fixes the following case:
* select all rows w/ "Select all" button
* deselect one of the selected rows
* "Select all" becomes unchecked
* select back unselected row
Problem: "Select all" expected to become checked again as all rows are selected but it's not.

fix(selection): properly update selectAll flag based on current selection

---

src/js/core/factories/Grid.js

There was already a fix, but handled differently. Not sure which way is correct, but this fixed my issue when using Cell navigation and pinning columns left. Hope this is helpful!
closes #4389

fix(core): scrollTo rightBound calculation

---

misc/tutorial/102_sorting.ngdoc
src/js/core/factories/GridColumn.js
src/js/core/services/rowSorter.js

Passing rowA and rowB to the sort functions allows the sorting functions to consider other fields when the sorting occurs. Passing direction is useful for such cases such as always having null values sorted at the bottom of the grid.

feat(sort): Give more information to the sort functions

---

src/features/grouping/js/grouping.js

Grouping fails when 'field' in columnDef is referred to some javascript object
than a primitive type. Resolves issue
[4493](https://github.com/angular-ui/ui-grid/issues/4493)

fix(grouping): When 'field' in columnDef is referred to some javascript object than a primitive type.

---

src/js/core/factories/Grid.js

Current documentation says Grid.prototype.handleWindowResize returns a Promise (https://github.com/angular-ui/ui-grid/blob/fe00489/src/js/core/factories/Grid.js#L263) but in fact the internal Grid.prototype.handleWindowResize method was never returning the Grid.prototype.queueRefresh promise (https://github.com/angular-ui/ui-grid/blob/fe00489/src/js/core/factories/Grid.js#L1513). This fix allows ui-grid users to wait until the grid is correctly sized before performing certain actions (like scrolling) which require an accurately-sized grid.

fix(core): Return promise from `handleWindowResize` method

---

src/js/core/factories/GridColumn.js

In documentation for cellClass function, parameters are incorrect.
In code, cellClass function is called with different parameters and order, see https://github.com/angular-ui/ui-grid/blob/master/src/js/core/directives/ui-grid-cell.js#L56

docs: Fix columnDef.cellClass documentation

---

src/js/i18n/ru.js

Some missed translations provided

i18n: add missing russian translations (#4349)

---

misc/tutorial/201_editable.ngdoc
src/features/edit/js/gridEdit.js

Add a new member to ColumnDef: editDropdownOptionsFunction:
a function returning an array of values in the format
[ {id: xxx, value: xxx} ], which will be used to populate
the edit dropdown.  This can be used when the
dropdown values are dependent on the backing row entity with
some kind of algorithm.
If this property is set then both editDropdownOptionsArray
and editDropdownRowEntityOptionsArrayPath will be ignored.

feat(edit): add a function to retrieve dropdown options

---

src/js/core/factories/GridColumn.js

As part of #4544 (where I updated documentation of footerCellClass), forgot to do the same for cellClass and headerCellClass. Parameters were incorrect in the documentation as well for these.
Reference to code:
https://github.com/angular-ui/ui-grid/blob/master/src/js/core/directives/ui-grid-header-cell.js#L219 (for headerCellClass)
https://github.com/angular-ui/ui-grid/blob/master/src/js/core/directives/ui-grid-cell.js#L56 (for cellClass)

docs: Fix incorrect parameters of cellClass and headerCellClass

---

src/js/core/directives/ui-grid.js

Today had a situation when grid did not adjust it height to minimum rows to show height. It turned out that rendered grid height was equal to `rowHeight` option value and so `autoAdjustHeight` was not called.
This [change](https://github.com/angular-ui/ui-grid/compare/master...ivanvoznyakovsky:fix-autoadjust-heigth?expand=1#diff-d586707ee1c4e842337e09afc6ebd587R280) fixes this.

fix(grid): adjust grid height when initial height is equal to row height

---

src/features/exporter/js/exporter.js

This is a fix for the Windows 10 users. Instead of using `.match` we
use `.search` which runs a boolean value. I noticed you guys were
trying to get the exact version of IE and that isn’t going to work for
Windows 10 users. I instead use the boolean value later to see if we
are even in IE. the `navigator.msSaveBlob` is a function in IE 10+ and
Edge so knowing that I can call that first and IE9 might possibly not
blow up. I haven’t gotten to officially test IE9 yet. If anything, this
PR is strictly a proof of concept. Feel free to message me with any
questions!

Fix For Windows 10 Exporter

---

src/js/core/directives/ui-grid-menu.js

Remove the reference to self inside uiGridMenu link method, thus avoiding memory leak.

(fix): Fix #4687 - Memory leaks - grid object not getting destroyed

---

src/js/core/factories/GridColumn.js

Fixes another leak found in issue #4687 (leak begins when switching between two pages with grids present).
Caused by GridColumn's hideColumn + unsort methods overriden prototype of all constructed GridColumns each time a GridColumn is constructed. Each of these methods kept a reference to grid via the self property in the closure scope.

4687 grid column leak

---

src/features/expandable/js/expandable.js

This is my first pull request for ui-grid, so hopefully I did it right.  I'm unfamiliar with your API documentation format.
This is a documentation-only change fixing issue #4724.

docs(expandable): add documentation for row.isExpanded

---

src/features/tree-view/less/tree-view.less

https://github.com/angular-ui/ui-grid/issues/4607
When Tree View and Select are both enabled, the Tree View expand button
did not work. The Tree View expand button was in a cell header class
who's click events are disabled. Enabling the pointer events on the
tree-header-row class resolves the issue.

fix(Tree View) Row expansion when Tree View and Select both enabled

---

src/js/core/factories/Grid.js

Change the way pixelsToSeeRow variable is calculated. This way
is possible to have different heights for rows and column headers.

fix(core): Fix #4776 scrollTo doesn't work with higher rowHeight

---

misc/tutorial/205_row_editable.ngdoc

in the line edited, the function that's being referred too must call setSavePromise, returning a promise as previously stated does not do anything as the result from events is ignored and not accessible to the caller.

fix missleading comment in row edit documents

---

src/less/icons.less

This path (../font) doesn't exists. 
When using bower it's searching font/ inside bower_components and broken assets minifiers like django pipeline.

Fix svg path. (icons.less)

---

src/features/tree-view/less/tree-view.less

In fix #4760 an override was introduced to allow clicking on the tree-expansion when row selection is on.  
The generated code with the grid options:
enableRowSelection: true,
enableFullRowSelection: true,
enableRowHeaderSelection: false,
render each cell with the following classes:
class="ui-grid-cell ng-scope ui-grid-disable-selection ui-grid-coluiGrid-0007 ui-grid-row-header-cell"
so, the order of these classes needs to have `ui-grid-cell` first, followed by `ui-grid-disable-selection` then `ui-grid-row-header-cell` in order for this override to work

re-order styles for tree-header-row override

---

src/features/move-columns/js/column-movable.js

redrawColumnAtPosition is called whenever you try to drag and move a column from one location to another.  However, if you move it and place it back in the same place, we should not trigger a full grid redraw.  There are already 2 conditions for when `originalPosition > newPostion` and when `newPostion > originalPosition`, but there is no case for when `originalPosition === newPosition` which should essentially mean... do nothing.
This PR will do just that.  Check to see if the column did not move, and return.  Therefore not raising any dataChanged or columnPositionChanged events.

skip redraw if column original position = new position

---

src/js/core/directives/ui-grid.js

I introduced a guard to reduce some unnecessary calls to `buildColumns` and `preCompileCellTemplates` each time data is changed. 
As a result, the `$q.all` promise in `dataWatchFunction` could resolve **before** promises created in previous calls. This is because an empty array of promises can be passed to `$q.all` the method now. This unearthed an issue where `modifyRows` could be passed outdated data from previous `dataWatchFunction` calls, rather than the most recent call.
Fixes #4532, issue introduced by #4428.

fix(uiGrid): Fix race condition in data watcher

---

src/features/move-columns/js/column-movable.js

Issue #3448 is caused by setting a left position to moving element relative to the browser viewport which will not take scroll position into account. By setting left position relative to moving element's parent, the problem will gone.

Fix #3448 Moving a column when the grid has horizontal scroll is broken

---

src/features/selection/js/selection.js
src/features/selection/test/uiGridSelectionService.spec.js

This method would help in implementations that show the number of selected items in a different way that the bottom info-bar.
Previously, the only ways to get the number of items are selected are less than ideal:
1) Call `getSelectedGridRows().length` on the API - this is slow because `getSelectedGridRows()` calls a filter on the entire dataset - which would be a performance drag if called every `$digest` cycle. One can avoid calling it on every cycle by binding a function that calls it to both `rowSelectionChanged`, and `rowSelectionChangedBatch`, but the resulting code is way less clear than simply `api.selection. getSelectedCount()`
Or 2) Render and hide the info bar, and try to parse its number. This should be avoided, as it's a hacky solution.
Since the number is already being held …

Add selection PublicApi method to expose selected count

---

src/features/pagination/js/pagination.js

Minor documentation, grammatical, and typographical clarifications.

Minor documentation improvements.

---

misc/tutorial/322_validation.ngdoc
src/features/validate/js/gridValidate.js
src/features/validate/less/validate.less
src/features/validate/templates/cellTitleValidator.html
src/features/validate/templates/cellTooltipValidator.html
src/features/validate/test/uiGridValidateDirective.spec.js
src/features/validate/test/uiGridValidateService.spec.js
src/js/i18n/en.js
src/js/i18n/it.js

This feature will make validation on fields possible.
It will not use angularjs basic validation because it wouldn't work when editing is over.
Instead it adds custom properties to field considered as invalid.
It provides a basic way to display error messages using html title attribute and a cooler one that depends on bootstrap to show a popover.
Tests and docs are provided.
For more info see issue #4152

feature(validation): add validation feature

---

src/js/core/directives/ui-grid-header-cell.js
src/templates/ui-grid/uiGridHeaderCell.html

Sort priority number indicators were added with #4257.  These look strange when only one column is sorted.  This pull request changes the indicators to only display when multiple columns are sorted.
fixes #4503

feat(sort): change sort priority indicator to only show when multiple columns are sorted

---

lib/grunt/plugins.js

The same contents saved to bower.json were being saved to package.json, generating an invalid package.json since the main attribute was an array instead of a string. Now this has been changed, and the package.json generated for distribution contains the same contents of the package.json file in the source code.
Fixes #4743

chore(build): change contents saved to package.json

---

src/features/saveState/js/saveState.js

There's currently an issue with the grid related to hiding columns and restoring saved column widths.
Here's a Plunker that shows the issue http://plnkr.co/edit/u1BHqBowywYhDhvnfc5R?p=preview
1. setup a grid with resizable columns and enableGridMenu = true, and saving and restoring the column widths from local storage
2. adjust the width of a column (make it big enough so you will notice the change when it reverts back)
3. save the grid state to local storage
4. refresh the page
5. restore the grid state
6. hide a column using the grid menu
once the column is hidden you will see that the column you resized will revert to it's original size. The cause is when column visibility is changed updateColumnDef is called which updates to column width from the columnDef if the column does not have …

fix(core): Fix columns reverting back to original size after restoring

---

src/features/saveState/test/saveState.spec.js
src/js/core/factories/Grid.js
src/js/core/services/rowSorter.js
src/templates/ui-grid/uiGridHeaderCell.html
test/unit/core/factories/Grid.spec.js

Before sort priority was a mix of 0 and 1 based.
You could create columns with a sort priority of zero but once the user
clicked on a column to sort it its index would change to 1. There was no
way for the sort index to return to 0 from within the grid's menus.
This mix of 0 and 1 based sorting was confusing and created UI problems
when displaying the sort index in the column header.
Closes #4685
BREAKING CHANGE:
**GridOptions.columnDef.sort.priority** now expects the lowest value
to be 0.
The Grid Header will display a sort priority of 0 as 1.
Using `if(col.sort.priority)` to determine if a column is sorted is no
longer valid as `0 == false`.
Saved grid objects may be affected by this.

fix(core): Sort Priority Zero Based

---

src/features/move-columns/js/column-movable.js

fixes the following issue:  "move columns broken in rtl #4643 "

fix(colMove): fix reversed column moving direction in RTL

---

src/js/core/directives/ui-grid.js

If you want to use fastWatch:true for data and columnDefs then the $watch handler needs to work with both fastWatch:true and false (or undefined). When mapping the incoming columnDefs with the internal columnDefs, always use what is on $scope instead of what the watcher is watching because the watcher is watching different things in the two different cases.
https://github.com/angular-ui/ui-grid/issues/3755

fix(core): Fix watcher handler columnDefs assignment

---

src/js/core/directives/ui-grid.js

defining a both a `filter` or `filters` property on a `columnDef` while alongside `options.enableFiltering === true` was resulting in one extra row's worth of height being calculated in `autoAdjustHeight`

fix(core): correct filter detection in autoAdjustHeight

---

src/js/core/directives/ui-grid.js

When in fastWatch mode, watcher methods returns the length of their array being watched. When this value (`int`). This value (`int`) is then being passed to the watcher's callback overwriting the array.

fix(#5041): Ensure length watchers transmit data

---

src/js/core/directives/ui-grid-header-cell.js

in Issue #4876 isSortPriorityVisible() is introduced.  However it is testing the variable rather than for undefined, so when element.sort.priority == 0, it is returning as false, even though that should return true.
This update is adding the checks for undefined
@jbarrus @JLLeitschuh

fix(core): check for undefined on sort priority

---

src/features/pagination/less/pagination.less
src/features/pagination/templates/pagination.html

When you browse pages in RTL, the first page is the rightmost. The button logic is OK, it's the buttons that were mirrored...

fix(rtl): Fixed pagination button direction in RTL

---

src/features/tree-base/js/tree-base.js
src/features/tree-base/templates/treeBaseHeaderCell.html
src/features/tree-base/test/tree-base.spec.js

Please consider pulling this commit.
Closes the mentioned issue.
Usage:
new supported gridOption
enableExpandAll
default value: true
Setting this value as false will hide the expand all button

feature(treeGrid): fix #3646 - allow to disable expand all button

---

src/js/core/services/ui-grid-util.js

Nice increase in scrolling performance when using mousewheel or trackpad

performance(core): add false flag to $timeout and $interval to prevent $apply

---

src/features/saveState/js/saveState.js
src/features/saveState/test/saveState.spec.js

Saves the page save and current page position when saveState is called, as long as pagination is enabled. Fixes #4146

fix(saveState): Fixes #4146 - Allow saving of pagination state

---

src/features/edit/js/gridEdit.js

This solves the problem angular-ui#4193 https://github.com/angular-ui/ui-grid/issues/4193
Only run elem.select() if it is available. Some custom renderers are not input of type text.

fix(edit): Error on opening custom cell editor who's first element has no select method

---

src/features/expandable/js/expandable.js

Features required for project I am currently working on.

feat(expandable): Add 'expandRow' and 'getExpandedRows' 

---

src/js/core/directives/ui-grid-column-menu.js
src/js/core/directives/ui-grid-menu.js
src/templates/ui-grid/uiGridMenu.html
test/unit/core/directives/ui-grid-menu.spec.js

For ARIA, an X and Close menu option had been implemented into the column menus.  This PR removes those and implements the ESC key to close the menu via a keyboard.  It also makes sure tabbing is cyclical, so tabbing continuously will keep you contained within the menu.

Removed the X and Close on menu, and implemented-ESC and cyclical tabs

---

CONTRIBUTING.md
README.md
grunt/aliases.js
grunt/shell.js
package.json

Commits will be validated before they can be created.
We now also support commitizen for commit message creation.

chore(commits): Adds Commit Hooks to build

---

src/features/auto-resize-grid/js/auto-resize.js
src/js/core/directives/ui-grid-menu.js
src/js/core/factories/GridApi.js
test/unit/core/directives/ui-grid-menu.spec.js

Closes #5090 
The grid menu enables a scrollbar to keep it's height under the height of the grid by 30px. However, it is only calculated when created. If auto-resize is on then the grid menu height does not get updated and therefore may get cut off. This PR adds a new event gridDimensionChanged to the gridApi which the menu can watch for to update it's style on change.

fix: Introduce gridDimensionChanged event

---

src/features/exporter/js/exporter.js

Write the correct csv header seperator. When `gridOptions.exporterCsvColumnSeparator` was set to something else than coma the header and the seperators are not equal and result in wrong behavior with excel.
In addition changed the ieVersion handling since it was broken due to #4640 for the csv part of the exporter.

fix(exporter): pass column seperator options as param to downloadFile

---

src/js/core/factories/Grid.js

No functional changes. Some of the comments were copied from the section above for row. The references needed to be updated to column/horizontal/left/right etc. to avoid confusion.

Fixing comments for horizontal scrolling to a column.

---

src/js/core/factories/GridRenderContainer.js

Firstly it is mentioned in #4046.
The way that scroll length is calculated was changed: it's encapsulated into a function and invoked in adjustColumns and scrollHorizontal. Before it was calculated differently.
In adjustColumns scrollPercentage was equal 1,01... instead of 1 when it was fully scrolled.

fix(core): Incorrect horizontal scroll percentage calculation

---

src/features/edit/js/gridEdit.js

One of my users discovered that if you hammer on an editable grid with dropdowns enough, you will occasionally end up with a dropdown left behind that should have been removed from the DOM. This fix makes sure that orphan dropdowns get cleaned up too.
After a quick look at your test suite, I could not come up with a good way to test for this bug, and they're not going to let me spend more time on this. I figured that the fix was still valuable though.

Fix intermittent bug where dropdowns are not properly removed after editing.

---

src/features/tree-base/js/tree-base.js

finaliseAggregations would bomb because the parent row is passed to it but does not exist when you set a row's entity $$treeLevel to -1 so that you can keep it non-parent row.
[See issue 5147 ](https://github.com/angular-ui/ui-grid/issues/5147)

Allows setting $$treeLevel to -1 on a row's entity

---

src/features/expandable/js/expandable.js
src/features/expandable/templates/expandableRowHeader.html
src/features/grouping/js/grouping.js
src/features/grouping/test/grouping.spec.js
src/features/selection/js/selection.js
src/features/tree-base/js/tree-base.js
src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

grid.addRowHeader api now takes a 2nd parameter, order, that is used to insert the row header in proper order.
For example, the order is now Grouping/Treeview row header, Expandable row header, then Selection row header if you use those features.
Also, expandable RowHeader is now hidden for Group summary rows
BREAKING CHANGE: It is possible that your application will show row headers in a different order after this change.
If you are adding rowHeaders, use the new order parameter in grid.addRowHeader(colDef, order) to specify where you
want the header column.

fix(core):  add row headers in order

---

src/js/core/directives/ui-grid-menu.js

There was a debug log statement in ui-grid-menu.js that was causing a log in the browser console any time the method itemAction was called. This has been removed.

removed log debug statement

---

test/e2e/gridTestUtils.spec.js

selectRow doesn't work when ui-grid-selection is enabled together with ui-grid-tree-view.
getRow returns first div in the row which will be the node expand/collapse icon's div if tree view is enabled.

Update gridTestUtils.spec.js (selectRow)

---

src/js/core/factories/Grid.js

The documentation for `refresh` method (line 218) should be updated to include optional param `rowsAltered`

docs(core api): update to include param rowsAltered

---

src/features/infinite-scroll/js/infinite-scroll.js

Resolves issue https://github.com/angular-ui/ui-grid/issues/5182

[infinite scroll] make sure more data is always loaded if scrolled to top/bottom quickly

---

src/js/core/services/ui-grid-util.js

now custom promise templates will handled properly, e.g.:
`headerCellTemplate: $http.get('./template.html').then(function(res) {return res.data;})`
fixes issue https://github.com/angular-ui/ui-grid/issues/4514

fix(getTemplate): Updated custom templates as promises condition

---

misc/tutorial/212_infinite_scroll.ngdoc

Remove $q dependency because $http already returns a Promise.
https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns
Replace deprecated $http success/error promise methods with then/catch
https://docs.angularjs.org/api/ng/service/$http

docs(infinite-scroll): remove $q dependency and deprecated $http promises

---

src/features/cellnav/js/cellnav.js
src/js/core/factories/GridRowColumn.js

GridRowColumn had an alternate implementation for getting the filtered value of a cell, possibly brought forward from ng-grid, but in certain situations, particular when handling cellFilters with parameters that were string literals, it would not always produce the correct output.  Grid already has a getCellDisplayValue with works perfectly (by storing the actual value, not attempting to duplicate all of angular's filter processing), and the single call in cellNav was the only place getIntersectionValueFiltered was being used.  Maintaining two functions that do the same thing in different ways, particularly when one is an attempted re-implementation of internal angular logic seems dangerous, so I'm proposing it be removed altogether in favor of using getCellDisplayValue.

fix(cellNav): notifyText incorrect if cellFilter had string literal parameter

---

src/js/core/services/gridClassFactory.js

This fix removes an unneeded additional function when setting
column visibility. Since both functions were of the same
priority level, it was possible that the visibility that
was passed in would be overwritten with the default value of
true under certain circumstances. There was really no need
for two functions, as this default behavior can be accomplished
in one. This fixes the following issue: https://github.com/angular-ui/ui-grid/issues/5303

Apply column visibility properly

---

src/services/DomUtilityService.js

Remove use of undocumented method jQuery.swap. See https://github.com/jquery/jquery/issues/2058
Tested with jQuery 2.2.4

Compatibility with jQuery 2.1.4 and above

---

src/features/selection/js/selection.js
src/features/selection/test/uiGridSelectionService.spec.js

The bug was that selectedCount would become incorrect if setSelected(x)
was called twice in sequence for the same row with the same x.

fix(selection): remove a logic bug in setSelected(..)

---

src/features/move-columns/js/column-movable.js
src/features/move-columns/test/column-movable.spec.js

This fix checks all the columns between the originalPosition and newPosition. IF they are all hidden, then no re-order event is necessary. If a visible column is found, column re-ordering will be triggered. This is an adjustment of #5255 as originalPosition is always a visible column.
Fixes: #5254

fix: prevent hidden columns triggering unnecessary re-order

---

CHANGELOG.md
bower.json
lib/grunt/plugins.js
package.json

package.json no longer accepts an array for it's main attribute, so releaseFiles is moved to files and main now receives a string "ui-grid.js". bower.json, however, will remain unchanged.  minified files now need to be included in "files" listing.
fixes: #4743

fix: package.json file packaging for deploying to npm

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

#4653: sort Priority 1 is presented as 0 in the sort object. It shows true for !column.sort.priority so it should be checked with column.sort.priority === undefined.
#4196: add function to decrease higher priorities if a column sort with lower priority is removed.
Added test cases to verify behavior.

Fix: bug wrong sort priorities #4653 and #4196

---

grunt/aliases.js

Updated aliases.js so that it reads in a grunt option for fontello and removes it from the build
task if fontello is set to false. This will fix issue #2304.

chore(grunt): Added a build flag to disable fontello

---

src/js/core/constants.js
src/js/core/factories/Grid.js
src/js/core/factories/GridColumn.js
src/js/core/factories/GridOptions.js

This commit documents the uiGridConstants entries that were observed to be used elsewhere in the API.
It is not necessarily exhaustive but does at least provide a listing of the more commonly used options
in the documentation.
Also corrects an incorrect type in the Grid.callDataChangeCallbacks documentation

docs(core): documented core uiGridConstants entries

---

src/features/move-columns/js/column-movable.js

When using jQuery, touch events are wrapped in new object (`event`) that removes the `event.pageX` property, causing column moving to break when used on mobile devices. However, jQuery stores the original native object in `event.originalEvent` ([docs](https://api.jquery.com/category/events/event-object/)).
If `event.pageX` is not set, this logic will instead use `event.originalEvent.pageX`, allowing column moving to work in conjunction with jQuery on mobile devices.

fix(columnMoving): handle touch events properly when jQuery is used

---

src/js/core/services/rowSorter.js

When glancing at docs, the module is displayed as 'RowSorter'. Users (like myself) might try to inject `RowSorter` instead of `rowSorter`, with resulting DI errors and frustration.

Change doc comments - 'RowSorter' to 'rowSorter'

---

misc/tutorial/323_more_binding.ngdoc
src/js/core/constants.js
src/js/core/factories/Grid.js
src/js/core/factories/GridRow.js
test/unit/core/factories/Grid.spec.js
test/unit/core/factories/GridRow.spec.js

This allows grids to be created for an array of primitives, such as
an array of Strings, and bind a column to each value in the data array
instead of having to bind to a property within each value.
Satisfies #5359

feat(core): Allow binding a column to the row entity itself

---

src/js/core/services/rowSearcher.js

The noTerm option was not being copied down to the internal filter
representation and so was preventing the filter being applied in
rowSearcher.searchColumn. This change ensures that flag is now
propagated correctly.
Resolves #5550 and #5551

fix(filter): Fix noTerm option for filtering

---

src/js/core/factories/GridColumn.js
src/js/core/services/rowSearcher.js

Adds the rawTerm option to the columnDef filter options, when enabled
it causes the rowSearcher to skip trimming and escaping the search term,
providing the raw value to the specified filter condition. This is
intended for use with custom search condition functions where pre-escaping
all regular expression characters or trimming whitespace is not desired.
Relates to #2475

feat(filter): Add rawTerm option to columnDef filter options

---

src/js/core/factories/Grid.js

Several issues and Stackoverflow threads indicate that one would expect the rowsVisibleChanged event to be emitted when a filter is applied. It seems pretty rational that rowsVisibleChanged ought to be raised by setVisibleRows(), which is what this small PR implements.
A related issue not addressed by this PR is that many of the SO threads and issues also seem to believe that a filtersChanged event should be raised after the visible rows are changed via filters. This is a common misunderstanding of how ui-grid operates in that changing filters are a different operation from changing visible rows. Since there seems to be a timing/ordering issue between when filtersChanged is raised and setVisibleRows is called this probably merits discussion before/if a change is made. Perhaps a tutorial …

fix(3901): Raise rowsVisibleChanged on setVisibleRows.

---

src/features/edit/js/gridEdit.js

minor change to solve errors when an element doesn't have a select function.
I ran into this problem when creating an edit cell template using a custom directive.

fix for error when element doesn't have the select function

---

src/features/expandable/js/expandable.js

I was not able to use a directive that requires a parent controller. A ctreq error is thrown.
Turns out that the sequence of appending and compiling was not correct. Maybe there are more situations like in that in the project... I haven't checked.
2 stackoverflow links that describes the problem:
http://stackoverflow.com/questions/21854814/angular-compile-with-required-controller
http://stackoverflow.com/questions/27644985/angularjs-dynamically-created-directives-require-not-working

Fix compile sequence to allow custom directives with required controllers to work

---

grunt/ngdocs.js

Fixing title link in documentation page.
Issue #5691

fix(#5691): Updating title link URL in documentation page

---

misc/tutorial/322_validation.ngdoc

Correcting issue with incorrect usage of the setValidator function in the validation tutorial.
Issue #5515

fix(5515): Fix validation documentation

---

src/js/core/constants.js

Copied list of all presently circulating currency symbols from Wikipedia per suggestion by
@MattiJarvinen-BA in Issue #3885. This should satisfy the TODO comment added by @c0bra.
Issue #3885

fix(#3885): Update currency symbols list

---

misc/site/data/5.json
misc/tutorial/218_empty_grid_base_layer.ngdoc
src/features/empty-base-layer/js/emptyBaseLayer.js
src/features/empty-base-layer/less/emptyBaseLayer.less
src/features/empty-base-layer/templates/emptyBaseLayerContainer.html
src/features/empty-base-layer/test/emptyBaseLayer.spec.js

This pull request adds a new feature 'emptyBaseLayer', that provides a background for the ui-grid, of continues rows, incase the height of the ui-grid is greater then the number of rows displayed.
This simulates a similar scenario as Excel, where the rows continue forever. The only exception is that the rows can't be edited, and just act as a background.
The rows/columns work with column resizing, and pinned rows.
A new tutorial page has been added. This is what it looks like in the tutorial:

Feature - Empty Base Layer

---

src/features/edit/js/gridEdit.js

The simplest possible solution i found to fixing an issue where selects with the "ui-grid-edit-dropdown" attribute would loose focus directly after getting it when trying to focus it with scrollToFocus while editing another field.
Simplified scenario: i have a textbox in the grid, if i type 2 i scrollToFocus to column 2, if i type 3 i scrollToFocus to column 3. This works great for all columns that isnt using the ui-grid-edit-dropdown attribute in the editTemplate. I compared the code for ui-grid-editor and ui-grid-edit-dropdown and noticed that ui-grid-editor has its elm[0].focus() inside a timeout. When applied to my issue this solved it,and it did not seem to cause any form of regression. Since it is already approved for use on the grid-editor attribute, i thought it would be …

fix:dropdown losing focus when using scrollToFocus from anoter editfield

---

src/js/core/factories/GridRenderContainer.js

example:
when the grid's total width is 150px, and we set column 1 to 25% and column 2 to 75%, column 1 will get rounded to 37px and column 2 will get rounded to 112px, leaving a 1px difference between the rows and the header. after fix, the column 1 will be 37.5px, column 2 will be 112.5px

Fix row width being shorter than header

---

src/features/cellnav/js/cellnav.js

Changes in doc (obvious mistake)

---

src/js/core/directives/ui-grid-menu-button.js

**Current Behavior**: Grid menu option _Clear all filters_ removes all filter `condition`s as well as search `term`s.
**Problem**: Users expect _Clear all filters_ to only remove search `term`s, but leave `condition`s as is so that filters can still be used to search the table. Essentially, we expect _Clear all fitlers_ to be the same as going through each filter and clicking the small _x_ next to it.
**Fix**: _Clear all filters_ only removes search `term`s and leaves `condition`s as is.
Fixes #4657

fix(core): Do not clear condition when clearing all filters

---

misc/tutorial/202_cellnav.ngdoc
src/features/cellnav/js/cellnav.js
src/features/cellnav/test/uiGridCellNavDirective.spec.js

Option to override default cell navigation
keyDownOverrides will force the viewPortKeyDown event
to be triggered if the specified key event was pressed
down, even if it is a default key command for the grid.
The handling of the event should then be done in the
viewPortKeyDown handler since the grid is no longer
handling the event.
This fixes issue: https://github.com/angular-ui/ui-grid/issues/4541

Option to override cell navigation defaults

---

src/js/core/services/ui-grid-util.js

e can be null in Firefox. This gives the styles is null error.
Add this extra !== null check and the error is gone.

ISSUE: 3782 (https://github.com/angular-ui/ui-grid/issues/3782)

---

src/js/core/factories/GridApi.js

The documentation for `gridApi.core.setRowInvisible()` and `gridApi.core.clearRowInvisible()` both specify a `rowEntity` as a parameter when in fact they require a `GridRow` instance. Both of these methods appear to expose the methods on the `GridRow` prototype which correctly documents the parameters.
This error in documentation may also be causing issues over at #3212

Correct parameter type for row visibility methods on gridApi

---

src/js/core/services/rowSorter.js

Return correct order when only one member has priority.

Correct priority sort. Fixes #5777

---

src/features/edit/js/gridEdit.js

Add mousedown listener to ui.grid.edit.directive:uiGridEditor to disable
blur handler if the element is a checkbox, and then re-focus the
checkbox and enable the blur handler after a $timeout. This change is to
deal with Safari and Firefox behavior in macOS where clicking the
checkbox causes a blur event, and the value is not updated.
GitHub issues: #1785, #4778, #4782

fix(edit): fix boolean edit issue on Firefox and Safari on macOS

---

src/js/core/factories/GridRenderContainer.js

If a grids viewport height, canvas height and scrollbar height has values so that the calculation:
canvas height - viewport height + scrollbar height returns 0, all the rows will dissapear when the grid is scrolled.

vertical scroll length should never be 0. This will result in division by 0 errors.

---

src/features/exporter/js/exporter.js
src/features/exporter/test/exporter.spec.js

I added a new option exporterMenuItemOrder for the gridOptions so that I could adjust where the items were showing up in the menu.

Option to adjust where the exporter showed up in the menu

---

src/features/selection/js/selection.js

When grouping and enableRowSelection is set to true clicking on plus/minus icons selects/deselects the row. This seems counter intuitive.
The problem was fixed by detecting where the click came from; in the case of an icon, it is ignored, otherwise a select/deselect action is triggered.

Prevent selection triggering on plus/minus click

---

src/features/infinite-scroll/js/infinite-scroll.js

Update uiGridInfiniteScrollService methods so they do **not** return promise of `adjustInfiniteScrollPosition` when `adjustInfiniteScrollPosition` does not itself return a promise.  Also updated documentation to match code changes.
Seems to be discrepancies between scroll events returning promises and not returning promises.  I think it's not a bad idea to return promises but `adjustInfiniteScrollPosition` calls `grid.scrollContainers` which doesn't return a promise so the promise chain doesn't actually exist.

fix(infinite-scroll): Remove returns of adjustInfiniteScrollPosition.

---

misc/tutorial/401_AllFeatures.ngdoc
src/features/cellnav/js/cellnav.js
src/features/edit/js/gridEdit.js

Fixes an issue where when ALL FEATURES are applied to grid and
enableCellEditOnFocus is set to true the edit event would not pass the
event to the beginEdit method causing issues with custom editors that
rely on the type of event that triggered the cell into edit mode.

Fixes issue #5799, eventOrigin not getting passed to begin edit when edit mode is triggered by cellNav

---

misc/tutorial/406_custom_pagination.ngdoc
src/features/pagination/js/pagination.js
src/features/pagination/templates/pagination.html
src/features/pagination/test/pagination.spec.js

Use Case:
Client requests page breaks by (e.g.) Date column. This can currently be
accomplished by external pagination, but the 'page size' dropdown
becomes irrelevant, and the page-count on the right can no longer
correctly determine the correct row range.
The pagination template has been modified to hide the page-size dropdown
when custom pagination is enabled, and to use new API methods for the
row range.
A new tutorial page has been added as lesson 406-Custom-Pagination
which demonstrates two usages: pre-sorted data, with pre-calculated pages
sizes; and unsorted data, with external pagination.

feat(pagination): Add custom pagination with variable page sizes

---

src/js/core/directives/ui-grid.js
src/js/core/factories/Grid.js
src/js/core/services/ui-grid-util.js

Angular's $timeout takes a boolean 3rd parameter which, if `false`, causes the wrapped function to not run inside $apply. Since $timeout is used extensively in core, this parameter has been passed where possible in order to improve performance. Previously, the grid would trigger a large number of digests even when working normally, see issue: https://github.com/angular-ui/ui-grid/issues/5007.
This is very low-hanging fruit. It is possible the same investigation can be applied across the plugins as well.

feat(core): Reduce digest triggers when using $timeout

---

src/js/core/directives/ui-grid-viewport.js

Can't find out a reason of issue, but it's reproduced easily in our application. This code fixes it.

Fix issue with space after the last table row

---

src/features/edit/js/gridEdit.js
src/features/move-columns/js/column-movable.js
src/features/selection/js/selection.js
src/js/core/directives/ui-grid-menu.js
src/js/core/directives/ui-grid-viewport.js
src/js/core/services/ui-grid-util.js

Adding a set of destroy listeners that unbinds jquery events when the grid is destroyed.
#4203

fix(memory_leaks): Ensuring events get unbound when grid is destroyed.

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

When using enableRowHashing (which is set right now to true as default), modifyRows match the old and the new row but not using the new entity at all.
Credit to @idangozlan for the fix. This PR merely adds unit tests to his [work](https://github.com/angular-ui/ui-grid/pull/4818).

fix(modifyRows): modifyRows uses the new entity when using enableRowHashing

---

src/js/core/directives/ui-grid-menu.js
src/js/core/factories/GridOptions.js
test/unit/core/directives/ui-grid-menu.spec.js
test/unit/core/factories/GridOptions.spec.js

Exposes gridMenuTemplate in gridOptions so that users can alphasort or custom sort their gridMenu items as needed. (may need to splice out the "Columns:" entry by user's custom sort)
**1 test is failing and I'm having issues isolating the root cause. Can you please advise?

feat(core): expose GridMenuTemplate

---

grunt/aliases.js
grunt/copy.js
grunt/cut-release.js
lib/grunt/plugins.js
misc/tutorial/101_intro.ngdoc
package.json

Fixing main section on bower.json and package.json. Adding index.js and CHANGELOG.md files to both and removing weird version folder with the font files.
#5776, #5558, #5432, #5027, #4484, #4324, #3402

fix(5776): Fixing bower.json and package.json configuration.

---

src/js/i18n/pt-br.js

Correction of translation in brazilian portuguese of the term "through". The literal translation was ok, but in the context of a grid it is not correct.

Fixed pt-br translation of 'through'.

---

src/features/tree-base/js/tree-base.js
src/js/core/directives/ui-grid-cell.js
src/js/core/directives/ui-grid-column-menu.js
src/js/core/directives/ui-grid-footer.js
src/js/core/directives/ui-grid-grid-footer.js
src/js/core/directives/ui-grid-group-panel.js
src/js/core/directives/ui-grid-header-cell.js
src/js/core/directives/ui-grid-header.js
src/js/core/directives/ui-grid-menu-button.js
src/js/core/directives/ui-grid-menu.js
src/js/core/directives/ui-grid-row.js
src/js/core/directives/ui-grid.js
src/js/core/factories/Grid.js
src/js/core/services/gridClassFactory.js
src/js/core/services/ui-grid-util.js

using sebastian-zarzycki-es solution i have added ".catch(angular.noop)" to all the offending promises on the latest 4.0.2 uigrid for angular 1.6.1

Angular 1.6 "Possibly unhandled rejection: canceled" fix. bug number #5890

---

src/js/core/factories/GridRenderContainer.js

Browsers affected: Firefox v51 for Windows
This is actually a firefox bug but I think ui-grid should support it. When a div has maxWidth and minWidth that are floats, sometimes the computed width of the div (for reasons I don't yet understand) gets rounded. Most notably, sometimes the width gets rounded up by up to 0.01 pixels so that the computed width is greater than the maxWidth. In a ui-grid, this can cause the divs to sum to larger than the parent row width which causes the last cell to spill to the next row (blurred for confidentiality): 
This Firefox bug is evident in the following plunker which was created based on the HTML/CSS output of our ui-grid: https://plnkr.co/edit/d85iZpOtJNmBl1YmRPCp - works fine on Chome and Firefox on Mac, but the computed div widths are slightly …

Force columns with width set by % be integer pixels

---

src/js/core/directives/ui-grid-menu.js

Currently, selecting a menu item in a ui-grid-menu cause focus to jump to the first item in the list.  This is a problem when the list of menu items is long.
Apply and test suggested fix from @tirithen in closed PR #4575
Demo Broken: http://take.ms/gSV7S
Demo Fixed: http://take.ms/UPEQk

Maintain focus on selected ui-grid-menu item.

---

src/features/resize-columns/js/ui-grid-column-resizer.js
src/features/resize-columns/test/resizeColumns.spec.js

Fixes Issue: enableColumnResizing accumulates watchers with each table $digest cycle #5101.
https://github.com/angular-ui/ui-grid/issues/5101
Creates a new scope for each resizer, stores them into an array so that the scopes can be destroyed before resetting the resizers.

Fix for Issue: #5101 - enableColumnResizing accumulates watchers with each table $digest cycle

---

src/features/pagination/js/pagination.js

Currently getLastRowIndex returns 1-based index and spoils, for example, rows range appearance in the pagination footer block. 
Related issue: #5944

make getLastRowIndex return 0-based index

---

misc/tutorial/401_AllFeatures.ngdoc
src/features/selection/js/selection.js
src/features/selection/test/uiGridSelectionDirective.spec.js
src/features/tree-base/js/tree-base.js
src/features/tree-base/test/tree-base.spec.js
src/js/core/directives/ui-grid.js
src/js/core/factories/Grid.js
src/js/core/services/ui-grid-util.js
test/unit/core/directives/ui-grid.spec.js
test/unit/core/factories/Grid.spec.js
test/unit/core/services/ui-grid-util.spec.js

Re-implemented some of @csvan's work with PR #5829 and improved refreshCanvas function.
Also, update the All features tutorial to add a toggle button for the filter row and improved coverage in ui-grid.js
5007

fix(5007): Reduced the amount of digest cycles initiated by the grid.

---

src/js/core/services/ui-grid-util.js

These changes cause e2e tests to fail in IE11

revert(ui-grid-util): Reverting changes to reduce digest cycle

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

For flatEntityDataAcess the `col.cellDisplayGetterCache` was always returning the first cached item for the column, and effectively ignoring the row parameter after the `col.cellDisplayGetterCache` had been set.
Closes #5773

Fix getCellDisplayValue with flatEntityAccess

---

src/less/body.less

Chrome v56 introduced a new feature called "scroll anchoring" which causes the scroll position to
update if element content above the current scroll position has changed. Since ui-grid-viewport updates the margin of the first line whenever a user is scrolling, scroll
anchoring will cause it to get into a scroll loop and scroll indefinitely (i.e. scroll to the end of
the grid). Credit to @Joel-Kornbluh

fix(6017): Fixes ui-grid-viewport scroll issue in chrome v56

---

src/js/core/directives/ui-grid-header-cell.js

When we sort columns with priorities, it was started from 0 in aria-labels

Sorting priority aria-label fix

---

misc/tutorial/324_default_sorting.ngdoc
src/js/core/factories/GridColumn.js
src/js/core/services/rowSorter.js
test/unit/core/row-sorting.spec.js

Default sorting allows data to always have an implicit ordering while yielding to any user-provided sorts. Default sorts effectively add additional columns to the sort at the lowest priorities, they cannot be removed and automatically reapply if the user clears their sort. Since they are intended to represent the default state of the data the default sorts are not displayed on the column headers and are effectively invisible to the user.
Regards,
Stewart A

feat(sorting): Default sorting

---

misc/tutorial/216_expandable_grid.ngdoc
src/features/expandable/templates/expandableRowHeader.html

Set a 'disableRowExpandable' property on the subGridOptions object to
control the visibility of the + icon for toggling the subGridVisiblity.
Solves the problem discussed @ http://stackoverflow.com/questions/33082810/angular-ui-grid-conditional-row-expand/33583355#33583355

Toggle subGrid controll visibility

---

src/features/saveState/js/saveState.js

Change restore to return the Promise created by grid.refresh() so additional functionality can be implemented after state has been restored and grid fully refreshed.

feat(saveState): change restore() to return Promise created by refresh()

---

src/js/core/factories/GridColumn.js

Add a warning about the name needing to be unique to
all instances of grids on a page because it can be used
as a key for retrieving custom sort algorithms, etc..

docs(columnDef): update name regarding uniqueness

---

src/js/i18n/de.js

The plural form of "items" (= "Einträge") in german is "Einträgen" of used like this in the pagination:
"1 of 30 items" => "1 von 20 Einträge**n**"

Fixed i18n typo in German language

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

In the scenario where cell edit and cell navigation is enabled the scrollPercentage will be greater then 1. But this only happens in the bottom row. The check prevents scrolling when this happens.

Prevent scrollEvent when scroll percentage is greater then 1.

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

Context
- When using columnName with special chars and grid has option flatEntityAccess: true, the function getCellDisplayValue is broken.
What changed
- Replace the string handed to $parse to use square brackets notation instead of dot
Related to https://github.com/angular-ui/ui-grid/issues/6270

fix #6270: Update getCellDisplayValue to manage special case with flatEntityAccess

---

misc/tutorial/210_selection.ngdoc
src/features/cellnav/js/cellnav.js
src/js/i18n/de.js
src/js/i18n/en.js
src/js/i18n/pl.js

Added feature to output aria-text for cells that come from selection feature ('selection ticks'). 
I added e2e test, but for unkown reason it causes next test suite to fail. It looks as if the next test fired before the page was actually loaded. Therefore I ignored the test. Does anybody have a clue, how can I make it work?
Besides I manually tested the feature with screen readers: NVDA and JAWS.

feat(cellnav): output aria text for cells that come from selection feature

---

DEVELOPER.md

Change from RowsProcessor to registerRowsProcessor where registration of the feature is being referenced.

docs(DEVELOPER.md): Fix typo

---

src/features/selection/less/selection.less

Before the focus on the selection row header could hardly be seen:
I therefore moved the opacity-property marking non-selected rows to the ::before-element to get a proper focus:

Focus on selection mark of unselected rows was hardly visible.

---

misc/tutorial/201_editable.ngdoc
src/features/edit/js/gridEdit.js

Let users know what triggered the edit request to be able to decide
if edit should be allowed or not.

feat(gridEdit): Pass triggerEvent to cellEditableCondition fn call

---

src/features/row-edit/js/gridRowEdit.js

rowEdit.flushDirtyRows may cause double row save
http://plnkr.co/edit/F0lXg3JtKzTgdZh2CqsA?p=preview
How to reproduce the problem:
- modify any value in the grid, for example Age
- immediately press Flush button on top
Flush button calls flushDirtyRows and saves dirty rows. Console prints "saveRow resolved".
About two seconds later rowEditSaveTimer save already saved row again. Console prints "saveRow resolved" second time

fix(rowEdit): cancel rowEditSaveTimer on flushDirtyRows

---

src/js/core/factories/Grid.js

Fixes #6197 by removing parseInt from the calculation of the header height.

Fixed grid height growing indefinitely with auto-resize.

---

src/features/cellnav/js/cellnav.js

This is an extension PR to https://github.com/angular-ui/ui-grid/pull/6260 There is a need of another PR concerning this, because what I have already done worked in Chrome, but not on Internet Explorer with JAWS screen reader. Therefore I ask to merge this PR into master branch as well. The fix is very simple, but it changes the semantics of aria implementation a little bit. You have used the aria-live attribute which should already work as a live region regardless of the role of the element, but unfortunately the JAWS screen reader doesn't see those live messages on Internet Explorer. It does see it when the role is set to 'alert'. It's not very pretty, but it's the only way it works on IE.

feat(cellnav): output aria text for cells that come from selection feature - works on IE with JAWS screen reader

---

src/features/edit/js/gridEdit.js

Firefox handling keypress event for function key. Then uiGridCellnav rise 'viewPortKeyPress' event with property which=0.
In uiGridEditor directive:
ngModel.$setViewValue(String.fromCharCode( typeof evt.which === 'number' ? evt.which : evt.keyCode), evt);
which = 0 and "String.fromCharCode(0)" returns this strange character.
fix #5770

fix #5770: verify that the keyCode is greater than zero

---

lib/grunt/utils.js

If a developer had defined a git tag which did not conform to the semver format "vx.y.z", the build
process would take this tag and assume it to be the current version but fail when it does not. The
script now skips these tags. It might also make sense to warn about these tags, as the developer may
have had a typo. But this still enforces the pattern to only have tags in that format.
Before this fix, if such a tag had been defined the following error message appeared:
```
$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'match' of null
```

fix(build): Cope with tags not conforming to semver format when building.

---

src/features/selection/js/selection.js

Fixes #6198 by using a more specific selector.

Fixed selection not being shown when empty base layer is enabled.

---

src/js/core/directives/ui-grid-filter.js
src/js/core/directives/ui-grid-footer-cell.js
src/js/core/directives/ui-grid-header-cell.js
src/js/core/services/gridClassFactory.js
test/unit/core/directives/ui-grid-filter.spec.js
test/unit/core/directives/ui-grid-footer-cell.spec.js
test/unit/core/directives/ui-grid-header-cell.spec.js
test/unit/core/services/GridClassFactory.spec.js

For URL-based templates we need to be sure that content arrived before `$compile` and `$elm.append` call.
This will close related issues: #4744, #5717, #5115, #5196, #5712, #5260, #5196, #4851, #4514, #5601.

Fixes URL-based template loading for `header-cell`, `footer-cell`, `filter`.

---

README.md
src/features/cellnav/js/cellnav.js
src/features/edit/js/gridEdit.js

Hi 
I think it can fix a bug that when enableCellEditOnFocus = 'true', when click a cell, this cell can be in the edit model correctly, but when leaving the same cell, then single click again, the edit model can not be triggered. Just double click can make the same cell editable again.
So for the changes in the cellnav.js, I made it can trigger navigation when clicking the same cell.
For the changes in the gridEdit.js, the original code is modified cause #4192 #4199), so that I add flag for clicking and keydown event, keep the scroll event same.
thanks

fix(edit): trigger edit when single click when enableCellEditOnFocus='true'

---

src/js/core/factories/Grid.js

I fixed an issue in a method in Grid prototype: getCellDisplayValue. The method has used the angular $parse service to cache the result of parsing the expression that should be evaluated to get the displayed value for a single cell. As we know from the documentation the $parse service returns a JavaScript function that can be called to retrieve the result of the expression evaluation when the argument should be the context which the expression should be evaluated in. The context in angular means: the scope.
In the deleted line of code in my commit the argument to the cached method was the row object though. This is incorrect. This should be scope. I assume that the developer that wrote this just wanted to make use of the service to, let's say, cache the expression evaluation, but the …

fix(Grid.js): wrong  use in getCellDisplayValue

---

src/features/pagination/templates/pagination.html
src/features/selection/templates/selectionHeaderCell.html
src/features/selection/templates/selectionRowHeaderButtons.html
src/templates/ui-grid/ui-grid.html
src/templates/ui-grid/uiGridRenderContainer.html

While there was no progress on #6269 I went on to talk to our accessiblity expert to fix the role-problems we have encountered so far.
To our understanding contentinfo and menubar should be removed without replacement as they are not applicable.
We went on to make the selection checkboxes accessible and present the grid as one grid similar to an example we have referenced in commit 066ba4c.
I understand that basic support has been added in 377485a by @JLLeitschuh. I see this as an expansion of this.

ARIA-Roles

---

src/features/pagination/js/pagination.js

If pagination is activated, the height of the ui-grid viewport has always been adjusted according to the height of the pagination control panel including its padding. This padding calculation resulted in unneeded margins under the horizontal scrollbar if the pagination is enabled but not needed. Now the height adjustment occurs only in case of shown pagination control panel.

fix(pagination): remove unneeded height adjustment

---

src/features/cellnav/js/cellnav.js

When overriding the default cell navigation, you will in some cases still need to trigger the default event handler. This very small change lets the developer retrigger the default behaviour if needed.
This is extending on the change made here: #5248 
Here is an example of how you could insert a new item, when the user presses tab while on the last cell in the last row, by using the added defaultHandler:
```
gridApi.cellNav.on.viewPortKeyDown($scope, function (evt, newRowCol, defaultHandler) {
var row = newRowCol.row;
var col = newRowCol.col
if (evt.keyCode === 9) {
if (
uiGridCellNavService.getDirection(evt) == uiGridCellNavConstants.direction.RIGHT &&
$scope.gridApi.grid.rows.indexOf(row) == $scope.gridApi.grid.rows.length - 1 &&
$scope.gridApi.grid.columns.indexOf(col) == …
```

Added default eventHandler to viewPortKeyDown

---

src/features/cellnav/js/cellnav.js
src/js/i18n/de.js
src/js/i18n/en.js
src/js/i18n/pl.js

Added functionality for ARIA. Now when user moves into a grid cell not only the content of the cell is read by the screen reader, but also the grid header for that cell. This is very helpful for a person who uses a screen reader, because he/she can not always easily find out under which column he/she is.

fix(Grid.js): add column header to text read by aria when user moves through grid with keyboard

---

src/features/expandable/js/expandable.js
src/features/expandable/test/expandable.spec.js

Resolved issue where clicking the "expand all" button opens sub grids that have disableRowExpandable set to true.
This leads to seeing ugly empty sub grid white space.  The fix simply includes a check for each row to see if expansion is disabled or not.

fix (expandable) expand all opens disableRowExpandable rows

---

src/features/selection/templates/selectionRowHeaderButtons.html

Hi,
Problem resolved with checkbox selection:
The tag i'not correct and show `role="checkbox" ng-model="row.isSelected"> ` after checkbox.

Problem resolved with checkbox selection:

---

src/features/resize-columns/js/ui-grid-column-resizer.js

There was subtraction which always returns zero: #5362
Now it's being calculated by new column width.

fix(resizing): zero delta on double click resizing

---

src/features/tree-base/js/tree-base.js
src/features/tree-base/test/tree-base.spec.js

Currently it's hard to expand a child under collapsed tree node(s).
This PR enable it without any change on existing behaviors.

feat(tree-view): Supports recursive expanding

---

src/js/core/factories/Grid.js

Stop preserving explicit header heights when styles are rebuilt. The buildStyles function fails to expand header height when it was previously set explicitly, and if explicit definition is needed it will be reset to the same value below.
fixes #3705

fix(uiGridHeader) stop preserving explicit header heights 

---

src/js/core/factories/GridColumn.js

If grouping is not activated and one have sorted three columns and then unsorted for example the second column using the column menu item "Remove Sorting", the remaining columns have got the priorities 1 and 3, not 1 and 2. This is now fixed with this commit.

fix(sorting): fixed the priority computing when unsorting using column menu action

---

src/features/auto-resize-grid/js/auto-resize.js
src/features/auto-resize-grid/test/auto-resize-grid.spec.js

In uiGridAutoResize there was cyckle which checked every 250ms for width or height change. I have implemented this same feature but based on watcher. So it shouldn't be  affecting the performance of your site or application negatively.

fix(uiGridAutoResize): Replaced timeout checker with watcher

---

test/unit/core/directives/ui-grid-column-menu.spec.js

Hi @mportuga 
this issue is related to this commit in 1.6.5, [$timeout/$interval: do not trigger a digest on cancel](https://github.com/angular/angular.js/commit/a222d0b452622624dc498ef0b9d3c43647fd4fbc), so there is no need to use $timeout.flush() for another digest. So as per test under 1.6, the test can also pass, so I just deleted.

test(ui-grid-column-menu): Fix test issue with angular 1.6.7

---

src/templates/ui-grid/ui-grid.html

The logic that sets the bottom-border-width for the last row calls a function that doesn't exist - grid.getTotalRowHeight() (issue logged in #4413) so I've updated it slightly to calculate this value using the grid.getVisibleRowCount() multiplied by grid.options.rowHeight which should achieve the desired effect of the original logic.

Fix bug with template for last row's bottom border

---

src/js/core/factories/GridRenderContainer.js

The change to using integer column widths means that we sometimes have some grid width left over where column widths are rounded down for asterisk or percentage widths, see #6371. The logic that then re-allocates the remaining widths currently only does this over columns with asterisk widths.
I've updated the logic to check if there are any asterisk columns and, if not, check for any percentage columns as a fall back. Only if there are no asterisk column widths, all columns are percentage widths and the percentages add up to 100%, then the percentage columns will be used to allocate remaining space, or trim if needed.

Fix bug of space to the right of the last column

---

src/js/core/factories/GridRenderContainer.js
test/unit/core/factories/GridRenderContainer.spec.js

After reading over the comments by @cwalther on issue #6474, I decided to revert some of the changes
done in commit 21819c5.
fix #6292, fix #6474, fix #6484

fix(GridRenderContainer): Fixing scrollbar styles.

---

misc/tutorial/207_importing_data.ngdoc
src/features/importer/js/importer.js
src/features/importer/test/uiGridImporterMenuItemDirective.spec.js

Updated the ui-grid-importer-menu-item directive to optionally require the uiGrid controller, much
like the regular ui-grid-menu-item directive.
fix #6535, fix #6009

fix(importer): Fix console error on opening grid menu.

---

src/js/core/directives/ui-grid-header-cell.js
src/less/footer.less
src/less/header.less
src/less/menu.less
src/less/variables.less
src/templates/ui-grid/uiGridHeaderCell.html
test/unit/core/directives/ui-grid-header-cell.spec.js

Fixed some of the more blatant issues of overlap between the grid menu and the last visible column,
although some issues remain with the timing of the digest cycle. Also, updated the grid menu styles
a bit based on some CSS suggestions.
fix #4337, fix #5051, fix #5557

fix(ui-grid-header-cell): Improved styles with grid menu.

---

src/features/importer/js/importer.js
src/features/importer/test/uiGridImporterMenuItemDirective.spec.js

Fixing issue which causes importer to not work ever.
fix #6550

fix(importer.js): Remove unnecessary on destroy event.

---

src/features/auto-resize-grid/js/auto-resize.js

We allow `elementWidth` and `elementHeight` call only once per 200ms to prevent from perf degradation.
This fixes #6561 and #6499.

Asking for grid $elm sizing in a digest loop always triggers `refresh`, not conditionally as designed.

---

src/js/core/directives/ui-grid-column-menu.js
src/js/core/directives/ui-grid-menu.js
src/less/header.less
src/less/menu.less
src/templates/ui-grid/uiGridMenu.html
test/unit/core/directives/ui-grid-column-menu.spec.js

Current behavior: https://plnkr.co/edit/Sr45hW2zhXcbPxvzEBTB?p=preview
New behavior: https://plnkr.co/edit/mSNHjvbSVCRklVrawk6m?p=preview
Since v3.0.0-rc.21, the column/grid menu animation slides down from
above the grid, but it is visible the entire time. This causes the
animation to appear clunky. This has been resolved by setting `overflow:
hidden` on the menu.
Fixes #3436, #3921, #3978.
Showing/hiding the menu can seem slow. The menu animation has been sped
up as well, and when it is hidden, the animation is now twice as fast.
Previously, to calculate the menu position, the width of the menu needed
to be calculated, which meant calling `repositionMenu` twice - once when
first opening the menu, and again after the menu is visible to allow the
width of the menu to be determined. This …

fix(menus): Fix menu positioning/animation

---

lib/grunt/utils.js

Since this browser is frequently the one that gives us issues for new changes and we are moving
towards angular 5 support, I am dropping it from our supported list.
BREAKING CHANGE: IE9 is no longer officially supported.
Closes #2273, #2552, #3593, #3854, #4439

fix(utils.js): Remove IE9 from supported browsers list.

---

src/js/core/directives/ui-grid-column-menu.js
src/js/core/directives/ui-grid-menu.js
src/less/header.less
test/unit/core/directives/ui-grid-column-menu.spec.js

Current behavior: https://plnkr.co/edit/kwyglaa2w9DxDmHtKt1Z?p=preview
Open the column menu for the first column.
New behavior: https://plnkr.co/edit/a2fLMi79c1W1WgKLxG82?p=preview
Menu width calculation was removed in #6588. Menu width needs to be calculated in order to properly position the menu (if there is not enough room to the left of the column). repositionMenu is now always called in the 'menu-shown' event listener to ensure the width can be properly calculated. Sorry I didn't catch this earlier.
The style attribute is removed from $elm in the 'menu-hidden' event listener to prevent the menu from appearing to slide from the left or right when opening another column menu while one is already open.
Menu animation speed was changed in #6588 to have different add/remove speeds. 0.04s …

fix(menus): streamline menu positioning

---

grunt/concat.js
misc/tutorial/104_i18n.ngdoc

Improving load performance of ui-grid.base.js by separating out the language files(with the
exception of english, as that is the default language of the grid).

feat(i18n): Separate language files from ui-grid.base.js

---

src/js/core/factories/Grid.js
src/js/core/factories/GridRenderContainer.js
test/unit/core/factories/Grid.spec.js
test/unit/core/factories/GridRenderContainer.spec.js

Added logic to needsHScrollbarPlaceholder to account for left/right rendercontainers as well as
handle case when gridOption enableHorizontalScrollbar is set to WHEN_NEEDED.
fix #6280, fix #5812, fix #5760, fix #6590, fix #6572, fix #6528, fix #4251, fix #3022

fix(WHEN_NEEDED): needsHScrollbarPlaceholder accounts for WHEN_NEEDED

---

misc/tutorial/209_grouping.ngdoc
misc/tutorial/215_treeView.ngdoc

Fixed property name (treeRowHeaderWidth --> treeRowHeaderBaseWidth), updated property description.

Update documentation for tutorials 209 & 215

---

src/js/core/factories/GridColumn.js
src/js/core/factories/GridOptions.js
test/unit/core/factories/GridColumn.spec.js
test/unit/core/factories/GridOptions.spec.js

GridOptions.minimumColumnSize is now used as the default minWidth for all columns when it is
provided and it is valid. However, minWidth will still take precedence over minimumColumnSize if
provided.
fix #3941

fix(GridColumn): Respect minimumColumnSize when a valid minWidth isn't present

---

src/js/core/factories/Grid.js
test/unit/core/factories/Grid.spec.js

Ensuring Select All button is disabled by default when no data is present.
fix #6582

fix(Grid.js): Select All button should be disabled when no data is present.

---

src/features/selection/js/selection.js
src/features/selection/test/uiGridSelectionService.spec.js

Added a check to verify if rows are selectable prior to selecting them.
fix #6370

fix(selection): SelectAllRows pays attention to isRowSelectable function

---

src/js/core/directives/ui-grid-column-menu.js
test/unit/core/directives/ui-grid-column-menu.spec.js

Provided keydown handlers for uiGridColumnMenu so you can tab-cycle through the menu items
correctly. Escape also now closes an open menu.
fix #5075

fix(ui-grid-column-menu.js): Added keyboard navigation to column menu

---

src/less/footer.less

fix(footer.less): Empty footer cells now take the full available height.

---

misc/tutorial/202_cellnav.ngdoc
src/js/core/factories/Grid.js

Updated the scrollToIfNecessary to treat any percentage number for the scroll position that is
greater than 1 as 1.
fix #6571, fix #6507, fix #6563

fix(Grid.js): scrollToIfNecessary can scroll to last row.

---

src/features/exporter/js/exporter.js
src/features/exporter/test/exporter.spec.js

Ensured that when exporterHeaderFilter and exporterFieldCallback are not defined, that the exporter
will respect the headerCellFilter and cellFilter attributes.
fix #6628, fix #5377, fix #5159

fix(exporter.js): Exporter will respect headerCellFilter and cellFilter.

---

src/js/core/factories/Grid.js

Doing this will prevent us from getting stuck in an infinite loop of triggering the scrollEnd event.
fix #6653, fix #4221

fix(Grid.js): ScrollIfNecessary will not scroll if percentage hasn't changed

---

src/features/importer/js/importer.js

Adding missing grid parameter to importerProcessHeaders example.
fix #5608

docs(importer.js): Fixing documentation.

---

src/js/core/factories/Grid.js

Since scrollIfNecessary is called multiple times when enableCellEditOnFocus is true we need to make sure the scrollbarWidth and footerHeight is accounted for to not cause a loop.
fixes #6653

fix(Grid.js): ScrollIfNecessary does not account for scrollWidth correctly

---

src/js/core/factories/Grid.js

Use scrollbarHeight instead of scrollbarWidth for vertical scroll calculations. scrollbarHeight has the value 0 when enableHorizontalScrollbar is set to NEVER.
Round calculated boundary values as computed style may have decimal number which will not match pixelsToSeeRow
Related to: #6653

fix(Grid.js) Vertical scroll calculates height wrong with enableHorizontalScrollbar: NEVER

---

src/features/cellnav/js/cellnav.js
src/features/edit/js/gridEdit.js
src/js/core/factories/Grid.js

Do not trigger a cell edit when the event is undefined, if needed through API pass a null object instead.
Fixes: #6591

 Fix(cellnav.js), do not trigger edit on undefined event

---

src/features/selection/js/selection.js

Allows selection from the checkbox on row headers when enableFullRowSelection is on.
fix #5239

fix(selection.js): Check if column is row header before disabling selection.

---

src/features/selection/js/selection.js

Change order of toggle to match toggleRowSelection function
fix #5411

fix(selection.js): Raise rowSelectionChangedBatch after toggling selectAll flag

---

src/features/selection/js/selection.js

* Allow group header selection.
* getSelectedRows will work on primitive data types.
fix #6698, fix #6704

 fix(selection.js): Group header and primitive data types.

---

src/js/core/directives/ui-grid-menu-button.js
src/js/core/directives/ui-grid-menu.js
src/less/menu.less
src/templates/ui-grid/ui-grid-menu-header-item.html
test/unit/core/directives/ui-grid-menu-button.spec.js

Fix accessibility of "Columns:" menu item by making it a heading instead of a button since it has no
action.

fix(ui-grid-menu-button.js): Change "Columns:" item to a heading.

---

grunt/connect.js
grunt/copy.js
src/less/variables.less

BREAKING CHANGE: If you take the new CSS and do not relocate the icon files your icons will cease to
show in the grid.
fix #3751

fix(fonts): Change font files path.

---

src/features/auto-resize/js/auto-resize.js
src/js/core/factories/Grid.js
src/js/core/factories/GridColumn.js
test/unit/core/factories/Grid.spec.js
test/unit/core/factories/GridColumn.spec.js

- Ensure displayNames can be empty strings
- Ensure scrolling is not lost on grid resize
- Ensure rows are refreshed when auto-resize is triggered

fix(ui-grid.core): Address resizing issues.

---

package-lock.json
src/templates/ui-grid/uiGridHeaderCell.html

The latest version of grunt-angular-templates adds an extra white space to the end of the header
cell label when it is minifying the html. By putting it all in one line, that issue is avoided.

fix(uiGridHeaderCell): Remove unncessary space

---

src/js/i18n/ja.js

Fixed Japanese translation about pagination.
"件" or "行" rather than "項目" is better suited for Japanese nuances.
In Japanese, "項目" means "cell".

fix: Japanese translation.

---

src/features/exporter/js/exporter.js

The default exporterExcelCustomFormatter custom function currently returns null which causes errors downstream. It should return the unmodified docDefinition
This should fix issue #6774

Default exporterExcelCustomFormatter shouldn't return null

---

src/features/validate/js/gridValidate.js
src/features/validate/test/uiGridValidateService.spec.js

* Although it was defined in the service (and in the docs), it was never exposed in the grid API's validate object.
* Fixes the ```validate.getErrorMessages is not a function``` error I was seeing.
* Also added unit tests.

fix(validate): missing getErrorMessages method

---

src/features/selection/js/selection.js
src/features/selection/less/selection.less

Focus row behavior from selection feature needs to be updated in order to prevent conflict.
fix #6782

fix(selection): Remove focus rows styles.

---

src/features/selection/js/selection.js

Revert part of 2485652
fix #6791

fix(selection): Fix multiSelect + modifierKeysToMultiSelect

---

src/less/header.less

Change grid header css to be flexbox based
Header display properties was previously table based while body is block based. This causes alignment issues between the two in some cases.
Note that if you have a custom header template based on table display properties, it will need to be updated to flexbox.
Fixes: #6799 #2592

Change grid header css to flexbox

---

misc/tutorial/112_swapping_data.ngdoc

Fix display error on Tutorial 112 by removing `/`s in the Tutorial name. [#6833]

docs(112_swapping_data.ngdoc): Fix display error due to use of /

---

src/features/tree-base/js/tree-base.js

Setting the $$treeLevel to undefined allows you to change a header row into a non-header row
Fixes #5548

(treeBase): allow setting row.$$treeLevel to undefined

---

README.md

"RawGit has reached the end of its useful life" and is shutting down according to https://rawgit.com.  They recommend using jsdelivr or another service.

Recommend jsdelivr rather than rawgit

---

src/js/core/services/rowSorter.js

When using this module with Webpack and UglifyJs, utilizing the compress with all default options will result in the sorting functionality breaking due to it hoisting and collapsing the propA and propB variables in the rowSortFn method. One simple solution to this issue is to wrap that content in an IIFE to prevent that hosting/collapsing behavior.

Wrap rowSortFn while innards in function to prevent sorting bug

---

src/js/core/directives/ui-grid-header-cell.js
src/js/core/factories/Grid.js
src/js/core/services/rowSorter.js

When doing a restore as part of saveState, it is possible to trigger the sort logic without having a
sort object, which causes failures.

fix(sort): add an extra check for sort data

---

src/features/selection/js/selection.js

This commit fix error shown in [#4608](https://github.com/angular-ui/ui-grid/issues/4608) taking care about start and end touch position to know if user want to click or scroll table.

fix(selection): prevent cell to be selected when user scroll

---

src/features/grouping/js/grouping.js

Change `the column which on which` to `the column on which`

fix(grouping.js): fix typo in description

---

grunt/concat.js

This should both fix the size of the ui-grid.js file and the broken selection feature.
fix #6927, fix #6928

fix(concat): only load ui-grid files once

---

packages/core/src/js/directives/ui-grid.js

Prevent uiGrid styles breaking(columns collapsing) for those cases when some uiGrids are invisible on page (in some hidden dialogs or tabs).
We don't need to do gridResize() when grid is not visible.

fix(core): prevent uiGrid styles breaking, columns collapsing

---

packages/core/src/js/directives/ui-grid-header-cell.js
packages/saveState/src/js/saveState.js

When using the filterChanged function, it's now possible to use the first argument - `column` - to simply do `column.filters[0].term` to retreive the search term for the column being filtered. This is especially useful if using external filtering.
I do not see a simple way to determine the column being changed without this.
Closes #4775.

feat(filterChanged): pass the changed column as first argument to filterChanged function

---

packages/core/src/js/directives/ui-grid-filter.js

Tested this code locally (I was having the same issue as the original poster for issue #6969). It works like a charm.
https://github.com/angular-ui/ui-grid/issues/6969

fix(ui-grid-filter): reset filterable on restored columns

---

packages/i18n/src/js/nl.js

The right translation of clearAllFilters in nl.js should be 'Alle filters wissen'. [#6738]

fix(translation): change translation in in i18n nl.js for clearAllFilters

---

packages/i18n/src/js/sv.js

Swedish translation of 'Items' is too specific. Change it to a more general translation.

fix(i18n): improve Swedish translations

---

packages/core/less/footer.less

From the version 4.4.4 we can observe an issue in the footer scroll (watch https://github.com/angular-ui/ui-grid/issues/6909).
To resolve the issue https://github.com/angular-ui/ui-grid/issues/6630 or https://github.com/angular-ui/ui-grid/issues/3416, it was added on footer.less some css styling (`
.ui-grid-footer-viewport,
.ui-grid-footer-canvas {
display: flex;
flex: 1 1 auto;
height: 100%;
}
` ). Actually you don't need to use flex properties to fix the upper issue, it's enough to add only just `height: 100%` and it will works fine. If you add the flex properties, you will produce the https://github.com/angular-ui/ui-grid/issues/6909, because the flex will modify the grid footer cell properties and the length of the footer will be longer then the grid content itself.

Scrolling - column footers misaligned with data #6909

---

packages/core/src/templates/ui-grid/ui-grid-header.html

**Issue Description:** Certain ARIA roles must contain particular children (.ui-grid-header-cell-row[role="row"]).This accessibility issue was found using [Accessibility Insights for Web 2.4.1](http://aka.ms/AccessibilityInsights) (axe-core 3.2.2), a tool that helps find and fix accessibility issues. I am using grouping in my project. I verified same on tutorial page. 
**Element path:**
.ui-grid-header.ng-scope[role="rowgroup"] > .ui-grid-top-panel > .ui-grid-header-viewport > .ui-grid-header-canvas > .ui-grid-header-cell-wrapper > .ui-grid-header-cell-row[role="row"]
**Environment:** Chrome version 74.0.3729.169 
**Fix Description:** Added role="columnheader" in children div element of row div.
**Before Changes: Required ARIA children role not present: cell columnheader rowheader …

update(ui-grid-header): added role attribute to UI-Grid-Header.html

---

packages/infinite-scroll/src/js/infinite-scroll.js

Hi there, I've been struggling with infinite-scroll upwards since last two days.
Whenever I am trying to scroll upwards, the scroll is very flickery(jumpy) and jumps to previous pages even when I am not scrolling.
I found out a plunkr today which I tried, and the scrolling seems to work.
http://plnkr.co/edit/DfXkANDYkBOmjauF1HmF?p=preview <= jumpy scroll. Inconsistent behaviour
http://plnkr.co/edit/33b8FAHHfNO0ryQ9oSD4?p=preview <= smooth scroll experience.
what the guy has does is that, he has removed the line
```scrollEvent.y = {percentage: 1/scrollHeight}``` with
```scrollEvent.y = {pixels: 1};```
And that fixes the issue.
Can anyone from the team check this and let me know if it is a bug which gets fixed by making this change.

Smooth scroll experience when scrolling upwards.

---

packages/core/src/js/directives/ui-grid-header-cell.js

**Issue Description:** User is unable to perform sorting actions using keyboard keys on Grid Column Header cell. We have to enable Column Header Menu to perform sorting through Menu option.
**Proposed Fix:** Updated **handleKeyDown** method to perform sorting on Enter and Spacebar keys in **ui-grid-header-cell.js** file.
**After Changes :** 
[AfterChanges_SortingWithKeyBoard.zip](https://github.com/angular-ui/ui-grid/files/3697168/AfterChanges_SortingWithKeyBoard.zip)
**Testing Details:** (Verified Locally)
Unit tests - PASS
Manual testing - PASS
E2E testing -  PASS
**Note:** CI build seems to be broken.

update(ui-grid-header-cell): enable sorting on grid header cell for enter & space-bar keys

---

packages/core/src/js/factories/Grid.js

When using custom `rowHeight` values, `scrollToIfNecessary()` works correctly going 'up' but not 'down'. On downward scrolls only the first 30px of the specified row is shown.
As far as I can tell, because the header isn't part of the `body` renderContainer then `headerHeight` should be removed from the `scrollToIfNecessary()` math. (Maybe the header used to be absolutely positioned within the render container?)
This also seems to be the case for `footerHeight` on 'upward' `scrollToIfNecessary()` scrolls but I haven't yet included a fix for this.
Am I misunderstanding something about the scroll containers or is this logic correct?
* Edit [this tutorial page](http://ui-grid.info/docs/#!/tutorial/Tutorial:%20202%20Cell%20Navigation) in Plunkr
* Set `gridOptions.rowHeight` to `80`
* Press …

Fix scrollToIfNecessary not working with custom rowHeight on downward scrolls

---

packages/exporter/src/js/exporter.js
packages/exporter/test/exporter.spec.js

Remove code that is adding a duplicate double quote for each double quote it sees in a string value when exporting from excel. Also change test file to reflect this change. The motivation is that it does not seem like normal behavior to add extra double quotes for excel exports and these extra double quotes become confusing for the end user.

fix(exporter): remove extra double quotes in excel export

---

packages/grouping/src/js/grouping.js

I believe this is a bug. The public API has a parameter that can be passed called 'aggregationLabel', but in the public API call, it is not used.
This pull request adds a check to the service to see if that aggregation label is a string and uses that as a label instead, as I believe it was intended.
Public API:

fix(grouping): adds aggregationLabel to aggregateColumn call to match public API

---

packages/exporter/src/js/exporter.js
packages/exporter/test/exporter.spec.js

Fix export all data to excel with treeview bug. Example: http://plnkr.co/edit/hFPAO6W3EW8nlzt2
fix #7127, fix #6819

fix: pass both tree parent nodes and children nodes when exporting

---

packages/expandable/src/templates/expandableRowHeader.html
packages/expandable/src/templates/expandableTopRowHeader.html
packages/expandable/test/expandable.spec.js

Adding the `aria-expanded` attribute allows the screen reader to let a visually impaired person know if an expandable area is expanded or collapsed.

feat: 🎸 add 'aria-expanded' to expand buttons for accessibility

---

packages/selection/src/js/selection.js

The issue we had was that we have rows that are selected, but also have `enableSelection: false`. We expected select all to behave similarly when selecting and unselecting all rows in that select all does not touch disabled rows. But unselect all does touch disabled rows.
This fixes the above issue by using the same check that is used during select all behavior in `clearSelectedRows`.

fix: clearSelectedRows should respect enableSelection 

---

packages/core/src/js/en.js
packages/i18n/src/js/es-ct.js
packages/i18n/src/js/es.js
packages/i18n/src/js/fr.js
packages/i18n/src/js/it.js
packages/i18n/src/js/pt-br.js
packages/i18n/src/js/pt.js
packages/selection/src/templates/selectionSelectAllButtons.html
packages/selection/test/uiGridSelectionSelectAllButtonsDirective.spec.js

Select All Checkbox needs a label and state to be announced by screen
readers.

fix: 🐛 ensure select all checkbox is announced correctly

---

packages/core/src/js/factories/GridColumn.js
packages/core/src/js/factories/GridRenderContainer.js

This PR allows width calculations to be float numbers instead of just integers. It allows for a more uniform distribution of columns and alignment with other grids.

fix(core): use allowFloatWidth property to allow float calculations for widths

---

packages/cellnav/src/js/cellnav.js
packages/core/src/js/directives/ui-grid-column-menu.js
packages/core/src/js/directives/ui-grid-header-cell.js
packages/core/src/js/directives/ui-grid-menu-button.js
packages/core/src/js/directives/ui-grid-menu.js
packages/core/src/js/en.js
packages/core/src/js/factories/GridRow.js
packages/core/src/templates/ui-grid/ui-grid-menu-button.html
packages/core/src/templates/ui-grid/uiGridHeaderCell.html
packages/core/src/templates/ui-grid/uiGridMenu.html
packages/core/test/core/directives/ui-grid-column-menu.spec.js
packages/core/test/core/directives/ui-grid-header-cell.spec.js
packages/core/test/core/directives/ui-grid-menu-button.spec.js
packages/core/test/core/directives/ui-grid-menu.spec.js
packages/core/test/core/factories/GridRow.spec.js
packages/i18n/src/js/es-ct.js
packages/i18n/src/js/es.js
packages/i18n/src/js/fr.js
packages/i18n/src/js/it.js
packages/i18n/src/js/pt-br.js
packages/i18n/src/js/pt.js
packages/selection/src/js/selection.js
packages/selection/src/templates/selectionRowHeaderButtons.html
packages/selection/test/uiGridSelectionDirective.spec.js

* add more keyboard handling and better announcements for checkboxes and
menus
* Adding translations for romance languages that I am familiar with.

fix: improve accessibility in the grid menus and selection

---

packages/core/src/js/services/rowSearcher.js

- updated escapeRegExp according to https://github.com/sindresorhus/escape-string-regexp (where it was originally probably taken from)
- now escapes term first, before changing *
- changed * replacement from "[\s\S]*?" to ".*?": [\s\S] == .
- fixes #7159 , #6335 and #5301

fix: 6360 error when entering *+ combination in the column filter

---

packages/core/less/body.less

- canvas now has a minimum height of 1px, which renders it even if it has no data and therefore preserving scrollability
- fixes #6898

fix: 6898 when filtering makes Data empty, the scroll is disabled and the column disappears

---

packages/core/src/js/factories/Grid.js
packages/core/src/js/factories/GridRenderContainer.js

- adjustColumns now calculates the colIndex instead of guessing it with scrollpercentage
- this is fixing #3527 
Use Case: grid has 100 columns, the first column is enlarged to 50% of grid width, it is scrolled to the middle(50%)
previously: assumes that all columns have the same width; 50% of 100 columns is 50 -> colIndex is set to 50; if excessColumns isn't high enough(default is 4) the cached Columns begin at Index 46
now: accumulates the drawnWidth of all columns till 50%(or whatever left position it has) and returns the index of the column which reached the treshold -> colIndex is set to 0; the cached Columns begin at Index 0

fix: 3527 Columns to the right disappear while Horizontally Scrolling

---

packages/cellnav/test/uiGridCellNavService.spec.js
packages/core/src/js/factories/Grid.js
packages/core/src/js/factories/GridRenderContainer.js

fix: 🐛 ensure viewport height cannot be negative

---

packages/cellnav/test/uiGridCellNavService.spec.js

Setting grid height prevents automatic grid heights from being generated
by the tests and failing randomly.

chore: 🤖 ensure gridHeight is constant to avoid inconsistencies

---

packages/core/src/js/services/rowSearcher.js

- null in filter is now changed to ''
- cleaned code
- **BREAKING CHANGE**: custom regex and filter may not work anymore. If thats a problem, then lines 182 and 183 could be moved 10 lines lower, below custom regex and filter call
this fixes #5502

fix: 5502 Column filter treat NULL as a string, so "n," "u," and "l" don't filter rows

---

packages/core/src/js/services/rowSorter.js

- scientific notation now also gets parsed to number on sort number string, including e, Infinity and -Infinity
- fixes #6388

fix: 6388 RowSorter doesn't sort numberStr in scientific notation correctly

---

packages/selection/src/js/selection.js
packages/selection/test/uiGridSelectionService.spec.js

Added parameter canBeInvisible to function toggleRowSelection which defaults to true, then it doesn't change the behaviour(so the user don't need to change anything).
When set to false, invisible rows won't get selected.
I also sat according unit tests.
this fixes #6418

fix: 6418 Selected groupings selects all of that column value no matter if filter is applied

---

packages/core/src/js/directives/ui-grid-style.js

- exchanged jquery's .text() function with more efficient direct assignment
- jquery btw also uses textContent: https://github.com/jquery/jquery/blob/de5398a6ad088dc006b46c6a870a2a053f4cd663/src/manipulation.js#L292
- fixes #4396

fix: 4396 Using .text() to set uiGridStyle is inefficient when using JQuery

---

packages/exporter/src/js/exporter.js
packages/exporter/test/exporter.spec.js

exporterCsvFilename, exporterPdfFilename, exporterExcelFilename and exporterExcelSheetName can now be functions.
They get the parameters grid, rowTypes and colTypes and should return the filename string.
This fixes #4446

fix: 4446 exporter file name setters now accept functions

---

packages/core/src/js/factories/Grid.js
packages/core/test/core/factories/Grid.spec.js
packages/selection/src/js/selection.js
packages/selection/test/uiGridSelectionService.spec.js

- fixes #4457
- I added find and select
- not just in entity but also in row object itself
- I can't guess what the id field of the user really is written, so after all keys can be searched
- new getter functions: _getRowsByKey_ and _findRowByKey_ (find returns only the first row which is more performant, User is responsible that this field is unique)
- new selector functions: _selectRowByKey_ and _unSelectRowByKey_, they both use findRowByKey
- all of them need following arguments: 
- isInEntity(boolean) toggles between row and entity object
- key(string or number) the specific key to the value
- comparator(any) the specific value, can be anything
- lookInRows(Array)(optional) same as in getRow(), search this instead of grid.rows

fix: 4457 Find or Select by Row Entity's 'ID'

---

packages/selection/src/js/selection.js

fix: issue when you clear the selected rows
I think is not necessary know if the row is selectable or not, I'm having on issue related to it. Imagine you have a select dropdown with actions to perform to the rows selected, you select some rows but then you change the action to perform and this new action is not allowed to some of the rows previously selected, the function is not going to clear up those rows because they are selected and then they are not selectables.

fix: clear selection function

---

packages/resize-columns/src/js/ui-grid-column-resizer.js

- width gets adjusted so that ellipses aren't shown
#7206

fix: 7206 double click column header doesn't make column wide enough

---

.github/workflows/pull_request.yml

This change will update the pull request build node version to 14

chore: use only node 14

---

packages/core/src/js/factories/GridRenderContainer.js

Change the order of conditionals to remove blank space between the last unpinned column and the pinned right column in order to fix the availableWidth behavior
#4949

fix(pinning): blank space between pinnedRight column and last unpinned column

---

packages/infinite-scroll/src/js/infinite-scroll.js
packages/infinite-scroll/test/infiniteScroll.spec.js

This change will prevent needLoadMoreData from being called on lastRow when cellNav is present. I did this because I was unable to edit the last row if both cellNav and infiniteScroll were present (caused infinte refresh loop with scrollDown).

fix: 🐛 don't call needLoadMoreData on last row with cellNav

---

packages/core/src/js/factories/Grid.js
packages/core/test/core/factories/Grid.spec.js

This change will update the index accordingly when newRow is added in modifyRows. I did this because index of row wasn't being updated properly when
- New row was added in the middle of rows
- More than two new rows were added
This fix resolves all the issues above.

fix: 🐛 update the index accordingly when modifying existing rows

---

packages/core/package.json

The upper limit for `angular` prevents the [long-term support version of AngularJS](https://xlts.dev/angularjs) from being used. The current version there is 1.9.3.
This PR removes the upper limit.

chore(core): remove upper limit for angular dependency

---

packages/core/src/js/factories/Grid.js

fix(core): make scrollToIfNecessary bottom scroll work with bottom pixel of the row

---

package-lock.json
package.json
packages/cellnav/src/js/cellnav.js
packages/cellnav/src/ts/cell-nav.constants.ts
packages/cellnav/tsconfig.json
tsconfig.json
webpack.config.js

This change will add support for typescript to the cellnav feature. I added this in order to start moving our code towards Angular.

chore(cellnav): add support for typescript
