- src/features/expandable/js/expandable.js
- src/features/exporter/js/exporter.js
- src/features/exporter/test/exporter.spec.js
- src/features/selection/js/selection.js
Modified exporter to accept a colDef attribute of `exporterSuppressExport`.
> Fix #2149 (expandable): set col to not export

- src/js/core/services/rowSorter.js
- test/unit/core/row-sorting.spec.js
Following the logic at https://adamfowlerml.wordpress.com/2013/04/02/stable-sorting-in-javascript/
> Fix #2534 (sort): implement stable sort logic

- src/features/move-columns/js/column-movable.js
> fix for issue #2601

- misc/tutorial/310_column_moving.ngdoc
- src/features/move-columns/js/column-movable.js
- src/features/move-columns/test/column-movable.spec.js
The commit has:
1. Fix for exception "can not access colDef of undefined" mentioned in #2632
2. Pinned columns can not be moved
> Column move fix for pinned columns

- src/js/i18n/zh-cn.js
- src/js/i18n/zh-tw.js
Add the missing part of pagination for chinese resources.
> Add pagination part for zh-cn.js and zh-tw.js

- src/features/saveState/js/saveState.js
> Add gridOptions.saveSelection = false support 

- src/features/saveState/js/saveState.js
Fix the condition that triggers the sort to change, it was firing incorrectly on every col
> Fix the condition that triggers the sort to change

- src/js/core/factories/GridRenderContainer.js
Fix infinite scrolling when rowIdentity is used.
> fix for #2811

- src/js/core/directives/ui-grid-menu-button.js
- src/js/core/directives/ui-grid-menu.js
- src/js/core/factories/GridOptions.js
- src/templates/ui-grid/ui-grid-menu-button.html
- test/unit/core/factories/GridOptions.spec.js
Reverts angular-ui/ng-grid#2845
> Revert "Bring back the 2.x menu behavior of custom menu templates."

- misc/tutorial/209_grouping.ngdoc
- src/features/cellnav/js/cellnav.js
- src/features/edit/js/gridEdit.js
- src/features/exporter/js/exporter.js
- src/features/grouping/js/grouping.js
- src/features/grouping/test/grouping.spec.js
- src/js/core/factories/Grid.js
A range of enhancements and fixes:
- grouping to have row count
- grouping to have stable sort on columns (not mess up sort order)
- cellNav to work with tab
- cellNav to work with editOnFocus
> Grouping enh and cellNav fixes

- src/features/edit/test/uiGridCellWithDropdown.spec.js
Change key of templateCache to use dropdownEditor in the test file.
And update element according to the latest template.
> Fix editDropdown test

- src/features/edit/templates/dropdownEditor.html
- src/features/edit/test/uiGridCellWithDropdownFilter.spec.js
change CUSTOM_FILSTERS position to enable filters
and add a test for editDropdownFilter
fixed #3000
> Fix editDropdownFilter

- misc/tutorial/105_footer.ngdoc
- misc/tutorial/110_grid_in_modal.ngdoc
- misc/tutorial/117_tooltips.ngdoc
- misc/tutorial/202_cellnav.ngdoc
- misc/tutorial/312_exporting_data_complex.ngdoc
- misc/tutorial/499_FAQ.ngdoc
- src/features/cellnav/js/cellnav.js
- src/features/expandable/js/expandable.js
- src/features/exporter/js/exporter.js
- src/features/grouping/js/grouping.js
- src/features/importer/js/importer.js
- src/features/row-edit/js/gridRowEdit.js
- src/features/saveState/js/saveState.js
- test/unit/core/directives/ui-grid.spec.js
- test/unit/core/factories/Grid.spec.js
- test/unit/core/services/ui-grid-util.spec.js
#3008: add more detail to modal tutorial for use of handleWindowResize
#3009: replace angular.forEach with array.forEach (and check for null where necessary first)
Fix failing e2e test in tooltip tutorial
#2989 dynamic width for grouping header column
#2921 exporter IE detection for IE 11 and 12 (untested, as no IE to test with)
#2962 cellNav, take gridFooter height into account
> Various fixes

- misc/site/data/100_ASC.json
- misc/site/data/100_DESC.json
Only first 25 objects are sorted make me confused when using external pagination, so sort all of them.
> Fix(sorting): sort all json data

- src/js/i18n/pt.js
Added Portuguese resource with pagination.
> Portuguese resource

- src/js/i18n/cs.js
Hi,
I've added Czech localization file for multiple key combination (cs, cz, cs-cz, cs-CZ). Tested on latest version.
Martin.
> Added Czech localization

- misc/tutorial/212_infinite_scroll.ngdoc
- src/features/infinite-scroll/js/infinite-scroll.js
- src/features/infinite-scroll/test/infiniteScroll.spec.js
1. Add a reset method and provide methods to allow removing data, extensions to tutorial to include
2. Change from infiniteScrollPercentage to infiniteScrollRowsFromEnd, makes the scrolling behaviour more controllable
> Adjustments to infinite scroll

- src/js/i18n/pt-br.js
Just added some missing translations to ptBR i18n file.
> Added missing translations for ptBR

- src/features/selection/js/selection.js
Tiny pull request - just noticed a typo whilst reading the docs
> Fix ngdoc typo for setSelected

- src/js/i18n/nl.js
avoid crash on  title: i18nService.get().grouping.group,       when language is set to dutch
> Update i18n nl.js for grouping feature

- src/js/core/services/rowSearcher.js
- src/templates/ui-grid/uiGridHeaderCell.html
- test/unit/core/row-filtering.spec.js
Filtering using a term that equaled 0 or false did not work as expected since the terms have been used directly in logical conditions.
> added support for filter terms equal 0 and false

- misc/demo/grid-save.html
- misc/tutorial/208_save_state.ngdoc
- src/features/pinning/js/pinning.js
- src/features/pinning/test/uiGridPinningService.spec.js
- src/features/saveState/js/saveState.js
- src/features/saveState/test/saveState.spec.js
The idea was to update saveState to include pinning. This turned
out to be more involved than initial anticipated. I ended up
having to update the pinning feature to include a public event
and method so saveState could include pinning as an option.
I updated documentation as I worked through it and even updated the
tutorial to include pinning. This is in reference to an feature
request I made recently #3123.
> feat(saveState): add pinning to save state

- misc/tutorial/306_expandable_grid.ngdoc
- src/features/expandable/less/expandable.less
- src/features/expandable/templates/expandableScrollFiller.html
- src/features/move-columns/test/column-movable.spec.js
The PR has fixes for:
1. #2793, custom class to be added for scroll filler of expandable grid.
2. #2793, Last few subgrids in expandable grid don't align with their "+" icon.
Also, today I added to PR fix for:
3. #2945, broken test cases of move column functionality.
> fixes for #2863 and #2793

- src/js/i18n/it.js
Add italian translations for the grouping feature. Activating grouping Without these will cause an error
> Update it.js - add grouping text

- src/features/cellnav/js/cellnav.js
- src/features/resize-columns/js/ui-grid-column-resizer.js
- src/js/core/directives/ui-grid-render-container.js
I can't recreate the situation, but this change should give a
clear error message if you hit the resizer api and it's not registered
> Fix(resize): fix #3183, resize module without the directive

- misc/tutorial/405_exporting_all_data_complex.ngdoc
- src/features/exporter/js/exporter.js
- src/features/exporter/test/exporter.spec.js
When using external pagination and want to use the native export function, this PR will do some help. Also see #2967 .
> Feat(exporter): export all till all data loaded

- src/features/pagination/test/pagination.spec.js
> Pagination tests working again

- src/js/i18n/fr.js
Hey there, 
here are some better translated i18n for french language
Regards, Olivier
> Fix(i18nService) : Minor fr translation fixes

- src/features/pinning/js/pinning.js
> fix(pinning): restore correct width state

- src/features/grouping/js/grouping.js
- src/features/grouping/test/grouping.spec.js
Fix a regression introduced in #3656
> Fix(grouping) Fix group by date with null values

- src/classes/eventProvider.js
Resolves conflicts between column resizing and dragging with IE browsers.
> drag and drop issues with IE

- src/js/core/factories/Grid.js
Fixes #3724
There is a typo in api.core function registration
> Fixes queue refresh api registration

- misc/tutorial/103_filtering.ngdoc
- misc/tutorial/208_save_state.ngdoc
- test/e2e/gridTestUtils.spec.js
208 was disabled because the cancelFilterInColumn method wasn't working
correctly however it seems to be working fine now.
> Enables e2e test on 208

- README.md
Adds links to the tutorial pages for all of the features as well as their respective API pages.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3988)
> Adds Links to Feature List

- src/features/pagination/templates/pagination.html
Not sure if the class names follow whatever convention has been established, but it would be nice to have these available for both styling and e2e tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular-ui/ng-grid/3987)
> add classes to pagination buttons

- README.md
Give people a good starting point if the want to contribute to the project.
> Provide Link to PRs Plz! Label in ReadMe

- README.md
Since https://github.com/angular-ui/ui-grid/issues/3658 is arleady closed.
> Extend Angular compatibility range in Readme

- src/js/core/directives/ui-grid.js
This fixes https://github.com/angular-ui/ui-grid/issues/4139
> fix(core): consider enableFiltering in autoAdjustHeight

- src/js/i18n/ta.js
Resolves the problems with #3610
> Fix for: Create ta.js

- src/less/bootstrap/bootstrap.less
- src/less/variables.less
Makes the bootstrap directory import use a variable so that it can be
overwitten.
Closes #3368
> fix(less): Makes less bootstrap dir a variable

- src/js/i18n/zh-cn.js
Completes zh-cn translation. Fix #4246.
> feat(i18n): Completes zh-cn translation.

- src/features/cellnav/js/cellnav.js
- src/js/core/factories/GridRowColumn.js
Moves the RowCol object to core and refactors it to be an object that
can be used by the entire library.
> feat(core): Adds GridRowColumn to core

- CONTRIBUTING.md
Fixes references to NG-Grid.
Also, adds link to gitter chat.
> docs(contributing): Updates references to ng-grid

- src/features/exporter/js/exporter.js
- src/features/exporter/test/exporter.spec.js
Modified exporter feature to consider visible pinned column among overall visible columns.
> Included pinned columns in export of visibile data. Fixed issue #3888.

- src/js/core/services/ui-grid-util.js
- test/unit/core/services/ui-grid-util.spec.js
Small fix for the `gridUtil.off.mousewheel` handler which wasn't working.
Also added some unit tests for `gridUtil.on.mousewheel` and `gridUtil.off.mousewheel`.
> fix(gridUtil): Fixes gridUtil.off.mousewheel event handler

- README.md
- misc/site/css/site.css
- misc/site/index.html
Makes the gitter chat buttons to more prominent locations.
This will hopefully help mitigate the number of issues and increase the
number of questions asked in chat.
> docs: Adds Gitter badge readme and site Homepage

- CONTRIBUTING.md
Adds some guidelines around git messages.
This will help get more commits into the changelog.
> Adds Commit Message Guidelines to Changelog

- src/js/core/factories/GridColumn.js
> Update GridColumn.js Documentation

- src/templates/ui-grid/ui-grid.html
This reverts commit a549eaa76c4a0fcb9cfd48f62cb4081b7734caf8.
> Revert "fix(Header): Use IE9 condcom to fix header sizing"

- src/js/i18n/cs.js
Please, include my Czech localization changes. I am native Czech speaker with grammar knowledge.
> Czech localization correction

- src/js/i18n/nl.js
Added missing pagination.of translation
> feat(i18n): completes nl translation

- misc/tutorial/103_filtering.ngdoc
- misc/tutorial/121_grid_menu.ngdoc
- src/templates/ui-grid/uiGridHeaderCell.html
- test/e2e/gridTestUtils.spec.js
> chore(e2e): Fixes the e2e tests

- src/js/i18n/da.js
Add sort translation. Improve aggregation.
> feat(i18n): improve da translation

- src/features/edit/js/gridEdit.js
Fix bug that adds an unintelligible character to cell input on edit.
Closes: #4588
> fix(edit): Change setViewValue to use a fromCharCode based on evt.which

- misc/site/css/site.css
- misc/site/index.html
More info about the sidecar can be found here: https://sidecar.gitter.im/
It looks like this when expanded. When compacted its a small little button in the right hand side of the homepage.
> chore(site): Adds Gitter Sidecar to Homepage

- src/features/pagination/js/pagination.js
- src/features/pagination/less/pagination.less
The code changes fix the pagination controls display issues in IE10 and
above
> Fix for Pagination styling is broken on IE9. #2552

- src/js/i18n/ro.js
Added romanian language translation .
> Romanian language

- src/js/i18n/pl.js
Polish translation based off english translation.
> feat (i18n): Polish translation.

- src/js/i18n/de.js
Thanks in advance for adding this translation which was missing
> added missing German translation

- .travis.yml
This should hopefully allow the fontello task to run properly
> chore(Build): Update node version to 4

- src/js/i18n/tr.js
I translated ui-grid texts to turkish. I hope it will be useful.
> feat(i18n): turkish(tr) translation

- src/js/i18n/tr.js
translation words changed for general usage.
> feat(i18n): turkish(tr) translation fix

- src/js/core/directives/ui-grid-header-cell.js
Fixes the column menu being hidden when columns are removed.
Closes #3953
> fix(core): Column Menu Hidden by Hiding Column

- src/js/i18n/de.js
Hi,
i added missing german translations wrt. the english original from en.js.
Please merge.
Kind regards
Dirk
> Add missing entries in comparison to en.js.

- src/js/core/directives/ui-grid-menu.js
- src/less/menu.less
- src/templates/ui-grid/uiGridMenu.html
- test/unit/core/directives/ui-grid-menu.spec.js
this fixes issue https://github.com/angular-ui/ui-grid/issues/4361
> feature(ui-grid-menu): grid menu does not extend past the grid bounds

- src/features/tree-base/js/tree-base.js
> fixed issue with expand all initialised as object.

- src/features/cellnav/js/cellnav.js
this is a pull request for: https://github.com/angular-ui/ui-grid/issues/4835
> Cellnav onnavigate called too often

- src/js/core/services/rowSorter.js
see why localCompare() is the best solution http://stackoverflow.com/a/26295229/759452
Fix as mentioned in https://github.com/angular-ui/ui-grid/issues/4811#event-490369609
> Update sorting so it can support internationalization

- src/features/exporter/js/exporter.js
- src/features/exporter/test/exporter.spec.js
> Add option when exporting to get the cell display value rather than the source value

- src/features/exporter/js/exporter.js
now Windows Edge can download the exported pdf file (Same behavior with IE)
> windows egde bug fix

- src/features/validate/test/uiGridValidateDirective.spec.js
- src/features/validate/test/uiGridValidateService.spec.js
Changed the way we used to simulate data edit.
I tested it with IE11 and Opera 12.16.
> feature(validation): fix tests on IE and Opera

- lib/grunt/plugins.js
Reverts angular-ui/ui-grid#4976
> Revert "chore(build): change contents saved to package.json"

- src/js/i18n/de.js
I am not sure where the keyword 'through' is used, so I only guess the meaning
> complete german translation of pagination labels

- src/js/i18n/ja.js
Add translation on pagination.
Fixes #4014
> fix(i18n): Add Japanese translation

- CONTRIBUTING.md
> docs(CONTRIBUTING): fix a typo

- .travis.yml
Travis will now build changes for any PR against the 3.x branch.
> chore(travis): Automatic builds on the 3.x branch

- src/features/expandable/js/expandable.js
Added expandableRowScope ngDocs
> Added expandableRowScope ngDocs

- misc/tutorial/110_grid_in_modal.ngdoc
- resizeHandler() now called 10 times, every 500 ms.
- Fixed comment to match tutorial description.
> Fix for resizeHandler() being called 500 times

- src/js/i18n/da.js
- src/js/i18n/no.js
My company noticed the grid menu for danish was not translated along with norwegian.  We got the ok from our company to submit the translations we are using from professional translators.  For existing danish file, I updated gridmenu section.  I added new norwegian file but only translated gridmenu section.  
Note: This is my first fork.  So let me know if I did something wrong.
Very nice work on the ui-grid everyone.
> Updated Danish and Norwegian GridMenu section

- misc/site/index.html
Fix link for project website, http://ui-grid.info/, link to Font Awesome css. Additionally use newer version of Font Awesome
> Fix Font Awesome CDN in website index.html

- src/js/i18n/de.js
> Typo in the German translation of gridMenu.exporterSelectedAsPdf.

- src/js/i18n/fr.js
Reverts angular-ui/ui-grid#5427
>  Revert "Add missing translations : Language French"

- package.json
Sauce keeps failing on master, this is the first attempt to fix it
> chore: Update karma-sauce-launcher to v1.0.0

- src/js/i18n/ua.js
Added file src/js/i18n/ua.js with Ukrainian Localization
> Added Ukrainian localization

- src/js/i18n/da.js
Added missing danish translations for pagination
> Added danish translations for pagination

- README.md
Adds the badge and content from open collective to the readme
> Add Open Collective to ReadMe

- src/features/validate/js/gridValidate.js
- src/features/validate/test/uiGridValidateService.spec.js
Please share comments if any. Thanks.
> fix for #5620: runValidators function does not return a promise 

- src/features/move-columns/test/column-movable.spec.js
adds unit tests for column moving on touch devices when jQuery is enabled
> test(columnMoving): adds tests for column moving on mobile devices

- src/features/grouping/js/grouping.js
Disable show count for columns of type object
Fixes #5705
> Fix 5705 grouping disable show count for columns of type object

- misc/site/customizer/index.html
- misc/site/index.html
Added a link tag to both the home page and the customizer to use existing favicon.
Issue #3899
> docs(favicon): Added favicon to ui-grid.info

- src/features/grouping/js/grouping.js
- src/features/grouping/test/grouping.spec.js
> fix #5711 restore original sort after group and ungroup

- test/unit/core/factories/Grid.spec.js
Adding missing parameters to GridColumn initialization.
> test(Grid.spec.js): Adding missing parameters to GridColumn initialization.

- src/features/expandable/js/expandable.js
Change the description of rowExpandedStateChanged event
> docs(expandable api): change the description of rowExpandedStateChangeEvent

- misc/tutorial/299_third_party_features.ngdoc
More information https://github.com/stevezau/ui-grid-auto-scroll
> Added ui-grid-auto-scroll third party plugin

- src/less/body.less
Fix for issue https://github.com/angular-ui/ui-grid/issues/5764
> fix ui-grid-expandable - columns mixing values after expand

- src/js/core/services/rowSorter.js
#5692 Exposing the column being sorted.
https://github.com/angular-ui/ui-grid/issues/5692
> Exposing the column being sorted

- grunt/aliases.js
> fix(build): Adding copy font task to build.

- test/karma.conf.js
- test/karma.debug.conf.js
Ensuring font files don't return a 404 during karma tests.
> fix(build): Adding proxis to karma.conf.js

- test/karma.conf.js
- test/karma.debug.conf.js
Trying to prevent socket hang up errors.
> 	fix(build): Adding file paths for proxies.

- grunt/karma.js
- misc/tutorial/407_custom_scrolling.ngdoc
- src/features/custom-scrolling/js/custom-scrolling.js
- src/js/core/directives/ui-grid-viewport.js
Adding support for providing a custom scroller and a new scroller that makes touch devices scroll without a lag between various pieces of the grid.
#1689, #3719, #5833
> feat(Scrolling): Adding support for a custom scroller.

- src/features/custom-scrolling/test/ui-grid-custom-scroller.factory.spec.js
Wrapping unit tests, removing event tests and destroying scroller.
> test(scroller): Refactor scroller factory test.

- CHANGELOG.md
- bower.json
- package.json
- src/js/core/directives/ui-grid.js
- src/js/core/factories/Grid.js
- src/js/core/services/ui-grid-util.js
This reverts commit 7e25a9b.
#5895
> fix(core): Adding back digest triggers when using $timeout

- src/js/i18n/pt-br.js
This reverts commit 33366f2f953f6fc8e4b50e309b0dc71d78655e26.
> Revert "Fixed pt-br translation of 'through'." to fix build

- src/js/i18n/bg.js
Added Bulgarian translations for UI-Grid elements.
> Add Bulgarian translations

- src/features/cellnav/js/cellnav.js
Only use the ngAria related functionality if the ngAria module has been loaded.
> Fix parse errors in cell navigation #5965

- src/features/move-columns/js/column-movable.js
- src/js/core/directives/ui-grid-header-cell.js
> delegate .ui-grid-cell-contents events

- src/features/edit/js/gridEdit.js
> gridEdit.js $elm.focus undefined bug fix

- src/features/move-columns/js/column-movable.js
- src/js/core/directives/ui-grid-header-cell.js
This reverts commit 7fc28dd0a1dd62787821c93b476698de6cc556ef.
> Revert "delegate .ui-grid-cell-contents events (#5997)"

- src/js/i18n/no.js
All resources translated to Norwegian, while preserving the style of the original translator.
Resolves issue #6061.
> Translated missing resources to Norwegian in no.js

- src/js/core/directives/ui-grid.js
- src/js/core/services/ui-grid-util.js
> fix(build): Removing performance improvements from ui-grid-util.js

- misc/tutorial/401_AllFeatures.ngdoc
- src/features/exporter/js/exporter.js
Also, fixing ui-grid-importer implementation on tutorial 401.
> fix(build): Fixing gridMenu undefined error.

- grunt/shell.js
Updating paths to support running tasks from windows.
> fix(shell.js): Adding windows support.

- misc/tutorial/401_AllFeatures.ngdoc
- src/features/selection/js/selection.js
- src/features/selection/test/uiGridSelectionDirective.spec.js
- src/features/tree-base/js/tree-base.js
- src/features/tree-base/test/tree-base.spec.js
- src/js/core/directives/ui-grid.js
- src/js/core/factories/Grid.js
- src/js/core/services/ui-grid-util.js
- test/unit/core/directives/ui-grid.spec.js
- test/unit/core/factories/Grid.spec.js
- test/unit/core/services/ui-grid-util.spec.js
Moving refreshCanvas call until after rows have been processed.
> fix(Grid.refresh): Refreshing canvas after processing.

- src/features/selection/js/selection.js
- src/features/selection/test/uiGridSelectionDirective.spec.js
Also, preping selection for future performance improvement.
> test(uiGridSelectionDirective.spec): Updating selection unit tests.

- src/features/tree-base/js/tree-base.js
- src/features/tree-base/test/tree-base.spec.js
Also, setting up tree-base to support future performance improvement.
> test(tree-base.spec): Updating tree-base unit tests.

- src/js/core/services/ui-grid-util.js
- test/unit/core/services/ui-grid-util.spec.js
Part 1: Reduce digest cylces in ui-grid-utils
#5007
> fix(5007): Reduced the amount of digest cycles initiated by the grid.

- misc/site/customizer/index.html
- misc/site/customizer/themes/paper.json
- misc/site/customizer/themes/themes.json
- misc/site/js/customizer.js
Also, adding more features to the grid visible in the customizer tool.
> feat(themes): Adding a new paper theme to the customizer tool.

- .travis.yml
- lib/sauce/sauce_connect_setup.sh
Updated Sauce Labs scripts to use latest version of Sauce Connect, per suggestion of the Sauce Labs team.
> fix(SauceLabs): Updating Sauce Labs scripts per suggestion.

- README.md
The scrollbar in the code block was bothering me so I cleaned up the build instructions.
> DOCS: update Readme.md

- misc/site/index.html
fix broken url for customizer on the homepage
> fix: broken customizer url on homepage

- misc/tutorial/307_external_sorting.ngdoc
Removing unknown broken link and weird sentence fragment.
> fix(ui-grid.info): Removing unknown broken link.

- misc/tutorial/312_exporting_data_complex.ngdoc
Mainly fix the HTML tag error & JS issue, the others(trim trailing whitespace) are auto completed by EditorConfig
> docs(tutorial 312): Fix HTML tag issue in tutorial 312

- src/js/core/factories/GridRenderContainer.js
> Fix #4949 - pinnedRight adding an extra blank column

- src/features/exporter/js/exporter.js
Extend the ability to customize pdf exports as mentioned in this issue.
https://github.com/angular-ui/ui-grid/issues/5227
> feat(exporter):Allow deeper pdf formatting options

- src/features/selection/js/selection.js
- src/features/selection/templates/selectionRowHeaderButtons.html
- src/features/selection/templates/selectionSelectAllButtons.html
- src/js/core/directives/ui-grid-header-cell.js
- src/templates/ui-grid/uiGridHeaderCell.html
- Fix the parameters of $scope.headerButtonClick in selection.js.
- Prevent space bar from scrolling on headers and selection cells.
> fix(selection): Prevent space bar scrolling

- .gitignore
- grunt/karma.js
- src/features/edit/test/uiGridCell.spec.js
- src/features/edit/test/uiGridEditService.spec.js
- src/features/edit/test/uiGridViewportDirective.spec.js
- src/features/infinite-scroll/test/infiniteScroll.spec.js
- src/features/tree-view/test/tree-view.spec.js
Improving code coverage for files in the Red.
> Code Coverage

- src/features/exporter/js/exporter.js
fix for issue #6163: exporterAllDataFn results was ignored.
> bugfix issue #6163

- misc/tutorial/203_pinning.ngdoc
- src/features/pinning/js/pinning.js
- src/features/pinning/test/pinning.spec.js
- src/features/pinning/test/uiGridPinningService.spec.js
Minor update for https://github.com/angular-ui/ui-grid/issues/2235 to allow hiding Pin left or Pin right option
> Added option to hide pinLeft or pinRight from pinning menu

- test/unit/core/directives/ui-grid-grid-footer.spec.js
- test/unit/core/directives/ui-grid-render-container.spec.js
Improving UI-Grid test coverage in order to make pre-merge builds more reliable and make it more likely that contributors will update unit tests/not introduce regressions.
> Improving Test coverage

- misc/tutorial/303_customizing_column_menu.ngdoc
- src/features/cellnav/js/cellnav.js
- src/features/exporter/js/exporter.js
- src/features/grouping/js/grouping.js
- src/features/tree-base/js/tree-base.js
- src/js/core/directives/ui-grid-header-cell.js
- src/js/core/directives/ui-grid-menu-button.js
- src/js/core/factories/Grid.js
- src/js/core/factories/GridOptions.js
- src/js/core/services/rowSearcher.js
- src/js/core/services/rowSorter.js
- src/js/i18n/ui-i18n.js
- test/unit/i18n/i18nService.spec.js
Credit to @cybermerlin for these great changes.
> chore(docs): fix broken docs and add info for column menu's trigger visibility

- misc/tutorial/101_intro.ngdoc
- misc/tutorial/102_sorting.ngdoc
- misc/tutorial/103_filtering.ngdoc
- misc/tutorial/104_i18n.ngdoc
Updating tutorials to follow Angular styleguide
> fix(tutorial): Updating some tutorial examples.

- misc/tutorial/121_grid_menu.ngdoc
- misc/tutorial/201_editable.ngdoc
- misc/tutorial/202_cellnav.ngdoc
- misc/tutorial/204_column_resizing.ngdoc
- misc/tutorial/212_infinite_scroll.ngdoc
- misc/tutorial/217_column_moving.ngdoc
- src/features/cellnav/js/cellnav.js
- src/features/edit/js/gridEdit.js
- src/features/infinite-scroll/js/infinite-scroll.js
- src/features/move-columns/js/column-movable.js
- src/features/resize-columns/js/ui-grid-column-resizer.js
- src/js/core/directives/ui-grid-column-menu.js
- src/js/core/directives/ui-grid-header-cell.js
- src/js/core/directives/ui-grid-menu.js
As stated by @kimmen on issue #6302 using applyAsync / evalAsync is probably a better practice than $timeout. So, this will hopefully help address a number of performance issues with UI-Grid.
I also took this opportunity to update the tutorials of all affected features to more closely follow the angular style guide standards.
> Replacing $timeout with $applyAsync

- src/js/core/directives/ui-grid-column-menu.js
- src/js/core/directives/ui-grid-menu.js
Reverting my previous change.
fix #6533
> fix(menus): Switching applyAsync for timeout.

- src/features/edit/js/gridEdit.js
- src/features/edit/test/uiGridEditFileChooserDirective.spec.js
Also, improving some code coverage.
>  fix(gridEdit): Fixing issues with focus and grid edit. 

- misc/tutorial/401_AllFeatures.ngdoc
Updating All Features tutorial to follow angular styleguide and prevent console error with
request.
> chore(401_AllFeatures.ngdoc): Fixing console error.

- src/features/edit/js/gridEdit.js
- src/features/edit/test/uiGridCell.spec.js
- src/features/edit/test/uiGridEditFileChooserDirective.spec.js
- src/features/importer/test/uiGridImporterMenuItemDirective.spec.js
>  fix(gridEdit): Fixing scrollToFocus issues. 

- misc/tutorial/209_grouping.ngdoc
- src/js/core/factories/Grid.js
- src/js/core/factories/GridOptions.js
fix #5016, fix #4756, fix #4627, fix #3930
> docs(ui-grid.info): Fix documentation issues.

- misc/tutorial/499_FAQ.ngdoc
> docs(499_FAQ.ngdoc): Fixing minor issues with the FAQ.

- src/js/i18n/ar.js
Added the Arabic translation to the Grid with abbreviation 'ar'.
> Add Arabic translation

- src/features/selection/js/selection.js
- src/features/selection/test/uiGridSelectionService.spec.js
- src/js/core/factories/GridRow.js
fixes issues #3911, #6126, #6145, #6263, #6398, and many others.
Tested the code for the company I work in, works very well with datasets approaching 5k records
> Correct behaviour for selection in tables that use grouping

- src/features/selection/js/selection.js
> chore(selection.js): Fixing build breaking.

- misc/tutorial/216_expandable_grid.ngdoc
- src/features/expandable/js/expandable.js
- src/features/expandable/templates/expandableTopRowHeader.html
- src/features/expandable/test/expandable.spec.js
- src/less/cell.less
- src/less/grid.less
> feat(expandAllButton): Add ability to hide expand all button.

- src/features/selection/js/selection.js
same as #6567, but only with the relevant changes
> Ensure that getting selected rows returns row entities, excluding the grouping entities

- src/js/i18n/pt-br.js
Displaying [MISSING] when trying to export as excel
> add pt-br excel translations

- misc/tutorial/122_accessibility.ngdoc
Fixing version of angular-aria on accessibility tutorial.
> fix(122_accessibility.ngdoc): Update angular-aria version.

- grunt/concat.js
- grunt/copy.js
- grunt/cut-release.js
> fix(ui-grid.core.js): Add missing i18nService to ui-grid.core.js

- src/js/i18n/de.js
change strings in gridMenu. Capitalized each first letter, added a
missing 'n'. Also added a missing 'e' at pagination - pageSelected
closes #6610
> fix(i18n)change some strings in de.js due to typos

- src/features/pagination/templates/pagination.html
https://github.com/angular-ui/ui-grid/issues/6596
> Limits pagination page number to integers only

- misc/tutorial/113_adding_and_removing_columns.ngdoc
> docs(GridColumns): Document show/hide column methods.

- misc/site/customizer/index.html
- misc/site/js/customizer.js
More of the features should are enabled so that you can see how your changes will affect the entire
grid.
Closes #3919
> docs(customizer): Add more features to customizer.

- src/js/core/directives/ui-grid-column-menu.js
Keyboard navigation fix suggested by @ShibyNiju
fix #6482
> fix(ui-grid-column-menu.js): Focus on first item in column menu on open.

- src/js/core/services/ui-grid-util.js
> fix(ui-grid-util.js): Comment out log statement.

- src/features/edit/less/edit.less
- src/features/resize-columns/less/column-resizer.less
- src/features/selection/less/selection.less
- src/features/selection/templates/selectionRowHeader.html
- src/features/validate/less/validate.less
- src/less/footer.less
- src/less/header.less
Fixes for the following issues: #4901, #5592, #6272 and an unlogged issue with the filter input boxes.
> Fixing various CSS issues

- src/features/pagination/less/pagination.less
Removed most float: left CSS and replace them with display: inline-block;
fix #4209, fix #2848
> fix(pagination.less): Pagination footer no longer overlaps last row.

- src/js/core/directives/ui-grid-menu-button.js
> docs(ui-grid-menu-button.js): Fix service name in documentation.

- src/features/tree-base/js/tree-base.js
- src/features/tree-base/test/ui-grid-tree-base-row-header-buttons.directive.spec.js
> fix(tree-base.js): Stop event propagation on click of the row header.

- src/features/pagination/less/pagination.less
- src/less/footer.less
> fix(pagination.less): Correct style pagination in footer info panel.

- src/js/core/directives/ui-grid-render-container.js
- src/js/core/factories/Grid.js
Also, revert 76e18d6 and format code for better readability.
fix #6480
>  fix(ui-grid-render-container): Use offsetHeight to avoid sizing issues.

- src/js/core/services/gridClassFactory.js
Credit to @NigmaX and @czyzm for coming up with the fix.
fix #4945
> fix(gridClassFactory.js): Move priority to correct spot.

- src/features/edit/js/gridEdit.js
- src/features/edit/test/uiGridEditFileChooserDirective.spec.js
> fix(gridEdit.js): Move deregister events until event conclusion.

- src/features/expandable/js/expandable.js
- src/features/expandable/test/expandable.spec.js
> fix(expandable.js): Update expandedAll attribute when toggling rows.

- src/features/selection/js/selection.js
> fix(selection.js): When enableSelection is false, row cannot be toggled.

- misc/tutorial/106_binding.ngdoc
- src/js/core/directives/ui-grid.js
Added back if statement in the dataWatchFunction and added an $eval to ensure controllerAs systax is
supported.
fix #6377, fix #6155
> fix(ui-grid.js): gridOptions.data string value now works again.

- src/less/footer.less
Removed flex-direction attribute which was causing issues.
fix #6654
> fix(footer.less): Footer column width now matches header column width.

- src/js/core/directives/ui-grid-menu-button.js
- test/unit/core/directives/ui-grid-menu-button.spec.js
> fix(ui-grid-menu-button.js): Replace show/hide buttons with a single toggle button

- src/features/exporter/js/exporter.js
Credit to @monster910 for making this fix.
fix #6676
> fix(exporter.js): Fix export when selection col is hidden. (#6676)

- src/templates/ui-grid/uiGridRenderContainer.html
> fix(uiGridRenderContainer.html): Prevent duplicate ids in the grid for ADA compliance.

- misc/tutorial/410_excel_exporting_data_and_header.ngdoc
- src/features/exporter/js/exporter.js
- src/features/exporter/test/exporter.spec.js
Just added these to complete the documentation
> Improve documentation for API for excel export

- src/features/tree-base/js/tree-base.js
- src/features/tree-base/templates/treeBaseExpandAllButtons.html
- src/features/tree-base/templates/treeBaseRowHeaderButtons.html
> fix(tree-base) Move tree expand button class to scope method

- src/js/i18n/da.js
Add missing pinning translations of Danish.
> fix(i18n): Add missing Danish pinning translations #6731

- src/features/auto-resize/js/auto-resize.js
- src/features/auto-resize/test/auto-resize-grid.spec.js
Reverted auto-resize code to a point where it worked a bit better and more consistent. Helps address
some cases of #6576.
>  feat(auto-resize): Add gridDimensionsChanged event, and revert some logic

- misc/tutorial/405_exporting_all_data_complex.ngdoc
Csv/Excel export not functioning properly on external pagination. [ #6727]
> docs(405_exporting_all_data_complex.ngdoc):

- src/features/selection/js/selection.js
- src/features/selection/less/selection.less
- src/features/selection/test/uiGridSelectionService.spec.js
- src/less/body.less
- src/less/variables.less
- Add enableSelectRowOnFocus option
- Add enableFocusRowOnRowHeaderClick option
- Add rowFocusChanged event
- Ignore multiSelect flag on selectCells if no keys are pressed.
- Replace $timeout with window.setTimeout
> feat(selection): Enhance the selection feature

- src/js/core/directives/ui-pinned-container.js
- src/js/core/factories/GridColumn.js
- src/js/core/services/gridClassFactory.js
- src/templates/ui-grid/uiGridViewport.html
- test/unit/core/factories/GridColumn.spec.js
- Cleaning up spacing in many files, with some refactoring
- Improve code coverage of GridColumn.js
> chore(ui-grid.core): Clean up and more tests

- grunt/copy.js
- grunt/cut-release.js
I missed a step when moving the fonts to their own folder and this addresses it.
fix #6759
> fix(fonts): Add missing fonts folder to release

- src/features/selection/less/selection.less
Fixes https://github.com/angular-ui/ui-grid/issues/6764
> fix(selection): selected row style only applied to left container

- src/js/i18n/es-ct.js
Added Catalan translations to the best of my ability with the help of Google translate and
translating from both English, Portuguese and Spanish to compare values. This should hopefully give
a reasonable translation.
fix #5536
> feat(es-ct): Add catalan translations.

- misc/tutorial/208_save_state.ngdoc
- src/features/row-edit/js/gridRowEdit.js
- src/js/core/factories/GridColumn.js
- src/js/core/factories/GridOptions.js
Documented headerRowHeight, sort priority, setRowsDirty and savePagination.
closes #4098, closes #5518, closes #5661, closes #6671
> docs(ui-grid.info): Added missing documentation.

- src/js/core/directives/ui-grid-render-container.js
- src/js/i18n/ui-i18n.js
- src/templates/ui-grid/uiGridRenderContainer.html
Refactoring and removing unnecessary code to improve performance.
> perf(ui-grid.core): Remove unnecessary code.

- misc/tutorial/209_grouping.ngdoc
Add missing tree-base dependency to the feature specific files section.
> docs(grouping): list tree-base dependency

- grunt/watch.js
- src/less/core.less
- src/less/elements.less
- src/less/main.less
- src/less/variables.less
The core.less file should serve to facilitate overwriting the variables in ui-grid.
fix #4659
> fix(less): create a core.less file for import

- src/features/tree-base/js/tree-base.js
Added fallback for when removing aggregations.
fix #5682
> fix(tree-base): agg: remove now works

- src/features/exporter/js/exporter.js
close https://github.com/angular-ui/ui-grid/issues/6869
> Fix csv export for object field type

- src/features/grouping/js/grouping.js
> (grouping): respect customTreeAggregationFn when grouping columns

- package-lock.json
- src/less/elements.less
- src/less/variables.less
Partial revert of commit 686658 since the customizer relies on those comments to work.
close #6834
> fix(customizer): update comments for customizer

- src/js/core/factories/GridOptions.js
- test/unit/core/directives/ui-grid-menu.spec.js
- test/unit/core/factories/GridOptions.spec.js
Exposes menuButtonTemplate and menuItemTemplate properties inside gridOptions similar to the gridMenuTemplate property.
> expose menuButtonTemplate and menuItemTemplate

- packages/auto-resize/README.md
- packages/cellnav/README.md
- packages/core/README.md
- packages/edit/README.md
- packages/empty-base-layer/README.md
- packages/expandable/README.md
- packages/exporter/README.md
- packages/grouping/README.md
- packages/i18n/README.md
- packages/importer/README.md
- packages/importer/package.json
- packages/infinite-scroll/README.md
- packages/move-columns/README.md
- packages/pagination/README.md
- packages/pinning/README.md
- packages/resize-columns/README.md
- packages/row-edit/README.md
- packages/saveState/README.md
- packages/selection/README.md
- packages/tree-base/README.md
- packages/tree-view/README.md
- packages/validate/README.md
Also, add missing dependency for importer.
> docs(ui-grid): add README to all packages

- grunt/uidocs-generator.js
> docs(ui-grid.info): fix reference to API documentation

- misc/tutorial/104_i18n.ngdoc
- packages/exporter/package.json
Also, fix path to ui-grid.core file in the i18n tutorial.
>  fix(exporter): remove unnecessary dependencies

- packages/i18n/src/js/es.js
Add Spanish translations for pagination controls
> feat(pagination): add Spanish translations for pagination controls

- packages/i18n/src/js/ru.js
Adds missing Russian properties for excel export and fix a typo in clearAllFilters property
fixes #6841
> fix(ru.js): add excel export properties ru.js + typo in clearAllFilters

- packages/core/src/js/services/ui-grid-util.js
> fix(ui-grid): #6937 getScrollBarWidth for Firefox

- misc/tutorial/116_fonts_and_installation.ngdoc
This is what failed for me. It might have failed for others, too, so it might help to include this information.
> doc: simplest fix is to include ui-grid.css

- packages/edit/src/js/gridEdit.js
… about possibly unhandled rejection
This is similar to issue https://github.com/angular-ui/ui-grid/issues/5890
> fix(edit): handle possible rejection on timeout

- packages/i18n/src/js/sv.js
Swedish translation for clearAllFilters wasn't correct and didn't make sense.
> fix(i18n): update clearAllFilters translation for SV

- packages/selection/src/js/selection.js
- packages/selection/src/templates/selectionRowHeaderButtons.html
- packages/selection/src/templates/selectionSelectAllButtons.html
- packages/tree-base/src/js/tree-base.js
- packages/tree-base/src/templates/treeBaseExpandAllButtons.html
- packages/tree-base/src/templates/treeBaseRowHeaderButtons.html
**Issue Description:** User is not able to access expand and selection buttons through key board.
**Proposed Fix:**  Added tab index and key down events for select and expand buttons.
**After Changes :** Please refer attached video. [AfterChanges_KeyBoardNavigation.zip](https://github.com/angular-ui/ui-grid/files/3733878/AfterChanges_KeyBoardNavigation.zip)
> update(keyboard-navigation): keyboard navigation changes of expand and selection buttons

- misc/tutorial/113_adding_and_removing_columns.ngdoc
Updated Plunker
http://plnkr.co/edit/2hqSGn5r4I3RU2BMlmQF?p=preview
> fix(core): update remove method as it was throwing error

- package-lock.json
- package.json
> fix: update angular to 1.8.0

- package-lock.json
- package.json
- test/karma.conf.js
- test/karma.debug.conf.js
mostly reverts 30f2ea3ff2ca134513058a853ad237c3d1660818
* installs karma-coverage to fix 'grunt coverage' task
* reverts to using karma-coverage in karma.conf files; this fixes
coverage when running 'grunt test'
* uninstalls karma-coverage-istanbul-reporter as it is not needed
This is done to fix the build as described in this issue https://github.com/angular-ui/ui-grid/issues/7091
> chore(karma): fixes coverage

- packages/core/src/js/services/ui-grid-util.js
Updated based on changes to jquery.rtl-support-type
> fix: 🐛 update rtl support function to fix rtl support

- packages/tree-base/src/js/tree-base.js
related to issue #5495, #5270, #5437, #7131
> fix(tree-base): grouping showing duplicate rows

- packages/i18n/src/js/de.js
- added missing german translation
- fixes: #7157
> fix: 7156 Missing german translation

- packages/core/src/js/services/rowSorter.js
- packages/grouping/src/js/grouping.js
- replaced null check with void check
- refactoring
was it already functioning? Anyway I refactored the sort
> fix: 3360 Sorting works inconsistently, when table column contains null/undefined/empty values

- packages/i18n/src/js/ru.js
update ru locale for i18n, as old one is not completely translated
> fix(i18n): complete ru locale

- packages/selection/src/js/selection.js
- packages/selection/test/uiGridSelectionService.spec.js
- added the functions unselectedRows() and getUnselectedGridRows()
- fixes #4850
> fix: 4850 getUnselectedRows Api

- packages/core/src/js/factories/Grid.js
- packages/selection/src/js/selection.js
clarified documentation of get and find Row by key
clarified documentation of selection by key
> fix: clarified documentation of 4.11.1 features

- package-lock.json
- package.json
We now rely on lerna to generate our changelog for us.
> chore: 🤖 remove grunt-conventional-changelog
